"""The owner's review queue: its arithmetic, and its drift check.

The committed `REVIEW-QUEUE.md` is a generated file, so the test that
matters most is the boring one — `--check` must fail the moment the
manifest and the queue disagree, the same discipline
`tests/test_contract_openapi_snapshot.py` applies to the OpenAPI
snapshot.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from src.content import loader, review_queue
from src.content.loader import default_content_root, load_path_dir
from src.content.review_queue import (
    REVIEW_QUEUE_FILENAME,
    build_queue,
    render_markdown,
)

pytestmark = pytest.mark.unit


@pytest.fixture(autouse=True)
def _clear_cache() -> None:
    loader.clear_cache()


def _entry(position: int, resource_id: str, url: str, **overrides: Any) -> dict[str, Any]:
    entry: dict[str, Any] = {
        "position": position,
        "resource_id": resource_id,
        "kind": "paper",
        "title": f"Paper {position}",
        "authors": ["A Name"],
        "author_count": 1,
        "year": 2020,
        "canonical_url": url,
        "license_note": "Link out to the arXiv abs page.",
        "attribution": "Someone et al. (arXiv.org)",
        "provenance": "curated",
        "status": "proposed",
        "rationale": "A rationale long enough to read like a sentence.",
        "vocabulary": ["a term"],
        "est_minutes": 60,
        "sequencing": {"method": "editorial", "cites": []},
        "briefing_file": f"briefings/{position:02d}.md",
        "briefing_provenance": "generated",
    }
    entry.update(overrides)
    return entry


def _document(**overrides: Any) -> dict[str, Any]:
    document: dict[str, Any] = {
        "manifest_version": 1,
        "path_id": "queue-path",
        "kind": "flagship",
        "title": "Queue path",
        "goal": "Exercise the queue.",
        "version": 1,
        "status": "proposed",
        "updated_at": "2026-08-30",
        "fixture": False,
        "licensing": {
            "posture_id": "W-OD-3",
            "full_text": "link-out-only",
            "abstracts": "displayed-with-attribution",
            "quotes": "sparing-and-attributed",
            "s2_derived_facts": "link-back-required",
            "commercial_use": "none-through-phase-w",
            "counsel_confirmed": False,
            "source": "planning/07-learning-platform/02-CONTENT.md#22-papers",
        },
        "review": {
            "owner": "kudratsingh",
            "decisions": ["W-OD-2", "W-OD-3"],
            "curation_minutes_per_entry": 30,
        },
        "generation": {
            "status": "deferred-awaiting-W-OD-2",
            "decision": "W-OD-2",
            "pipeline": "the research pipeline",
            "command": "do-not-run-this",
            "max_budget_usd": 5.0,
            "est_cost_usd_per_briefing": 0.5,
            "est_review_hours_per_briefing": [1.0, 2.0],
            "note": "Deferred.",
        },
        "entries": [
            _entry(1, "arxiv:1706.03762", "https://arxiv.org/abs/1706.03762"),
            _entry(2, "arxiv:1810.04805", "https://arxiv.org/abs/1810.04805"),
        ],
    }
    document.update(overrides)
    return document


def _briefing_text(resource_id: str, path_id: str) -> str:
    header = {
        "resource_id": resource_id,
        "path_id": path_id,
        "provenance": "generated",
        "label": "generated, human-reviewed",
        "briefing_version": 1,
        "generated_by": "job-test",
        "generated_at": "2026-08-30",
        "reviewed_by": "kudratsingh",
        "reviewed_at": "2026-08-30",
    }
    body = (
        "> **Generated by the learning agent, reviewed by kudratsingh.**\n\n"
        "Why this paper, why now: because the test needs a body.\n"
    )
    return f"<!-- provenance\n{json.dumps(header)}\n-->\n\n{body}"


def _write(root: Path, document: dict[str, Any]) -> Path:
    directory = root / "paths" / document["path_id"]
    (directory / "briefings").mkdir(parents=True)
    (directory / "path.json").write_text(json.dumps(document), encoding="utf-8")
    return directory


class TestQueueArithmetic:
    def test_curation_and_briefing_hours_are_reported_separately(
        self, tmp_path: Path
    ) -> None:
        """The split is the point: one half is startable, one is blocked."""
        path = load_path_dir(_write(tmp_path, _document()))
        queue = build_queue(path)
        assert queue.curation_hours == (1.0, 1.0)  # 2 entries x 30 min
        assert queue.briefing_hours == (2.0, 4.0)  # 2 briefings x 1-2 h
        assert queue.total_hours == (3.0, 5.0)

    def test_the_briefing_half_names_the_decision_that_blocks_it(
        self, tmp_path: Path
    ) -> None:
        path = load_path_dir(_write(tmp_path, _document()))
        queue = build_queue(path)
        assert {item.blocked_by for item in queue.briefings} == {"W-OD-2"}
        assert {item.blocked_by for item in queue.curation} == {None}

    def test_an_approved_entry_leaves_the_curation_queue(
        self, tmp_path: Path
    ) -> None:
        document = _document()
        document["entries"][0].update(
            status="approved",
            reviewed_by="kudratsingh",
            reviewed_at="2026-08-30",
        )
        directory = _write(tmp_path, document)
        (directory / "briefings" / "01.md").write_text(
            _briefing_text("arxiv:1706.03762", "queue-path"), encoding="utf-8"
        )
        path = load_path_dir(directory)
        queue = build_queue(path)
        assert [i.resource_id for i in queue.curation] == ["arxiv:1810.04805"]
        # ...and its briefing leaves the briefing queue with it, because
        # a reviewer is what "reviewed" means.
        assert [i.resource_id for i in queue.briefings] == ["arxiv:1810.04805"]

    def test_a_link_out_never_enters_the_briefing_queue(
        self, tmp_path: Path
    ) -> None:
        document = _document(
            entries=[
                _entry(
                    1,
                    "ext:some-course",
                    "https://course.example.org/",
                    kind="external_course",
                    briefing_file=None,
                    briefing_provenance=None,
                )
            ]
        )
        path = load_path_dir(_write(tmp_path, document))
        queue = build_queue(path)
        assert queue.briefings == ()
        assert len(queue.curation) == 1


class TestRendering:
    def test_the_rendered_queue_names_every_enforced_rule(
        self, tmp_path: Path
    ) -> None:
        """So the reviewer knows what not to spend the hours on."""
        rendered = render_markdown(
            build_queue(load_path_dir(_write(tmp_path, _document())))
        )
        for rule in review_queue.ALL_RULES:
            assert f"`{rule}`" in rendered

    def test_the_rendered_queue_carries_every_rationale(
        self, tmp_path: Path
    ) -> None:
        path = load_path_dir(_write(tmp_path, _document()))
        rendered = render_markdown(build_queue(path))
        for entry in path.manifest.entries:
            assert entry.rationale in rendered

    def test_the_deferred_campaign_is_stated_with_its_ceiling(
        self, tmp_path: Path
    ) -> None:
        rendered = render_markdown(
            build_queue(load_path_dir(_write(tmp_path, _document())))
        )
        assert "deferred-awaiting-W-OD-2" in rendered
        assert "$5.00" in rendered
        assert "do-not-run-this" in rendered

    def test_a_point_estimate_renders_without_a_fake_range(
        self, tmp_path: Path
    ) -> None:
        rendered = render_markdown(
            build_queue(load_path_dir(_write(tmp_path, _document())))
        )
        assert "1 h |" in rendered
        assert "1–1 h" not in rendered


class TestDriftCheck:
    def test_check_passes_on_the_committed_queue(self) -> None:
        assert review_queue.main(["--check", "--root", str(default_content_root())]) == 0

    def test_check_fails_when_the_manifest_moves(self, tmp_path: Path) -> None:
        directory = _write(tmp_path, _document())
        assert review_queue.main(["--write", "--root", str(tmp_path)]) == 0
        assert review_queue.main(["--check", "--root", str(tmp_path)]) == 0

        document = _document(version=2)
        document["entries"][0]["rationale"] = "A different reason entirely, honest."
        (directory / "path.json").write_text(json.dumps(document), encoding="utf-8")
        loader.clear_cache()
        assert review_queue.main(["--check", "--root", str(tmp_path)]) == 1

    def test_check_fails_when_the_queue_file_is_missing(
        self, tmp_path: Path
    ) -> None:
        _write(tmp_path, _document())
        assert review_queue.main(["--check", "--root", str(tmp_path)]) == 1

    def test_invalid_content_exits_two_not_one(self, tmp_path: Path) -> None:
        """A broken manifest is a different failure from a stale queue."""
        directory = tmp_path / "paths" / "broken"
        directory.mkdir(parents=True)
        (directory / "path.json").write_text("{ not json", encoding="utf-8")
        assert review_queue.main(["--check", "--root", str(tmp_path)]) == 2

    def test_no_queue_is_generated_for_a_fixture_path(
        self, tmp_path: Path
    ) -> None:
        """Nobody reviews scaffolding; a queue for it would be noise."""
        document = _document(
            path_id="fixture-path",
            kind="fixture",
            fixture=True,
            banner="FIXTURE CONTENT. Scaffolding.",
            entries=[
                _entry(
                    1,
                    "arxiv:1706.03762",
                    "https://arxiv.org/abs/1706.03762",
                    briefing_file=None,
                    briefing_provenance=None,
                )
            ],
        )
        directory = _write(tmp_path, document)
        assert review_queue.main(["--write", "--root", str(tmp_path)]) == 0
        assert not (directory / REVIEW_QUEUE_FILENAME).exists()


class TestShippedQueue:
    def test_the_flagship_queue_is_the_ten_to_twenty_hours_02_budgets(
        self,
    ) -> None:
        path = loader.load_content_root(default_content_root())[
            "reading-first-papers"
        ]
        queue = build_queue(path)
        assert queue.briefing_hours == (10.0, 20.0)
        assert len(queue.briefings) == 10

    def test_the_curation_half_is_startable_today(self) -> None:
        """The part of the review that no owner decision blocks."""
        path = loader.load_content_root(default_content_root())[
            "reading-first-papers"
        ]
        queue = build_queue(path)
        assert len(queue.curation) == 14
        assert all(item.blocked_by is None for item in queue.curation)
        low, high = queue.curation_hours
        assert 2.0 <= low <= 3.0
        assert low == high

    def test_the_committed_file_is_what_the_generator_produces(self) -> None:
        path = loader.load_content_root(default_content_root())[
            "reading-first-papers"
        ]
        committed = (path.directory / REVIEW_QUEUE_FILENAME).read_text(
            encoding="utf-8"
        )
        assert committed == render_markdown(build_queue(path))
