"""Offline labeling packets, the blinding key, and the agreement report.

Every label in this file is **synthetic and generated here**. No expert
has labelled anything, and a real label would not be checked in: the
retention rule for human labels is still an open owner decision
(14 §12, §14). The synthetic annotator below is a perfect one with three
deliberate errors — one false pass, one false fail, one abstention — so
the report's arithmetic is checkable against counts a reader can derive
from the registry by hand.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Final

import pytest
from pydantic import ValidationError

from src.calibration.__main__ import main
from src.calibration.labels import (
    Confidence,
    LabelType,
    binary_outcome,
    decision_vocabulary,
)
from src.calibration.packets import (
    DEFAULT_OUTPUT_ROOT,
    INSTRUCTIONS,
    MANIFEST_HANDLING,
    PACKET_IDS,
    BlankResponse,
    CompletedPacketItem,
    CompletedResponse,
    LabelPacket,
    ManifestEntry,
    PacketItem,
    PacketKey,
    PacketManifest,
    PacketMaterial,
    PacketSet,
    RateSummary,
    SubmittedLabel,
    build_packet_set,
    ingest_labels,
    load_registered_cases,
    registered_blinding_plan,
    render_report,
    write_packet_set,
)

pytestmark = pytest.mark.unit

_ROOT: Final = Path(__file__).resolve().parents[1]
_DOC: Final = _ROOT / "docs" / "agent-engineering" / "14-judge-calibration-protocol.md"

#: The registry's composition, re-derived below rather than trusted. The
#: report numbers every assertion in this file quotes follow from it.
_ITEMS: Final = 30
_BINARY_ITEMS: Final = 24
_PAIRWISE_ITEMS: Final = 6
_REFERENCE_FAILS: Final = 16
_REFERENCE_PASSES: Final = 8


@pytest.fixture(scope="module")
def packet_set() -> PacketSet:
    return build_packet_set()


@pytest.fixture(scope="module")
def doc() -> str:
    return _DOC.read_text(encoding="utf-8")


def _decision_with(label_type: LabelType, outcome: bool) -> str:
    for value in decision_vocabulary(label_type):
        if binary_outcome(value) is outcome:
            return value
    raise AssertionError(f"{label_type} has no {outcome} decision")


def _synthetic_decisions(
    packet_set: PacketSet, packet_id: str
) -> tuple[dict[str, str], tuple[str, str, str]]:
    """A perfect annotator with exactly three deliberate errors.

    Returns the decisions *as the annotator would write them* — pairwise
    preferences in the order this packet displayed — plus the three ids
    that were perturbed, so a test can name them.
    """
    entries = {
        entry.blinded_item_id: entry
        for entry in packet_set.manifest.key_for(packet_id).entries
    }
    cases = {case.blinded_item_id: case for case in load_registered_cases()}
    binary_ids = sorted(
        item_id
        for item_id, entry in entries.items()
        if entry.label_type is not LabelType.PAIRWISE_PREFERENCE
    )
    fails = [
        item_id
        for item_id in binary_ids
        if binary_outcome(cases[item_id].expected_decision) is False
    ]
    passes = [
        item_id
        for item_id in binary_ids
        if binary_outcome(cases[item_id].expected_decision) is True
    ]
    assert len(fails) == _REFERENCE_FAILS
    assert len(passes) == _REFERENCE_PASSES
    false_pass_id, abstain_id = fails[0], fails[1]
    false_fail_id = passes[0]

    decisions: dict[str, str] = {}
    for item_id, entry in entries.items():
        expected = cases[item_id].expected_decision
        if item_id == false_pass_id:
            decisions[item_id] = _decision_with(entry.label_type, True)
        elif item_id == false_fail_id:
            decisions[item_id] = _decision_with(entry.label_type, False)
        elif item_id == abstain_id:
            decisions[item_id] = "abstain"
        elif entry.presentation_order == "ba" and expected in {"first", "second"}:
            decisions[item_id] = "second" if expected == "first" else "first"
        else:
            decisions[item_id] = expected
    return decisions, (false_pass_id, false_fail_id, abstain_id)


def _completed_packet(
    packet_set: PacketSet,
    packet_id: str,
    decisions: dict[str, str],
    *,
    annotator_id: str = "ann-expert1",
) -> dict[str, Any]:
    payload: dict[str, Any] = packet_set.packet(packet_id).model_dump(mode="json")
    payload["annotator_id"] = annotator_id
    for item in payload["items"]:
        item["response"] = {
            "decision": decisions[item["blinded_item_id"]],
            "confidence": "high",
            "rationale": "Synthetic decision generated by the test suite.",
        }
    return payload


def _label_file(
    packet_set: PacketSet,
    packet_id: str,
    decisions: dict[str, str],
    *,
    annotator_id: str = "ann-expert2",
) -> dict[str, Any]:
    entries = packet_set.manifest.key_for(packet_id).entries
    return {
        "schema_version": "1.0.0",
        "packet_id": packet_id,
        "annotator_id": annotator_id,
        "labels": [
            {
                "blinded_item_id": entry.blinded_item_id,
                "label_type": entry.label_type.value,
                "decision": decisions[entry.blinded_item_id],
                "confidence": "medium",
                "rationale": "Synthetic decision generated by the test suite.",
            }
            for entry in entries
        ],
    }


def _write(path: Path, payload: Any) -> Path:
    path.write_text(json.dumps(payload), encoding="utf-8")
    return path


@pytest.fixture()
def written(tmp_path: Path, packet_set: PacketSet) -> Path:
    """The packet set on disk, returning its directory."""
    write_packet_set(tmp_path)
    return tmp_path / packet_set.packet_set_id


class TestWhatTheAnnotatorSees:
    def test_the_packets_carry_the_material_and_nothing_that_answers_it(
        self, packet_set: PacketSet
    ) -> None:
        cases = load_registered_cases()
        assert len(cases) == _ITEMS
        real_ids = {case.case_id for case in cases}
        blinded_ids = {case.blinded_item_id for case in cases}

        assert [packet.packet_id for packet in packet_set.packets] == list(PACKET_IDS)
        for packet in packet_set.packets:
            assert {item.blinded_item_id for item in packet.items} == blinded_ids
            assert packet.annotator_id is None
            assert packet.instructions == INSTRUCTIONS
            rendered = packet.model_dump_json()
            assert not real_ids.intersection(rendered.split('"'))
            for forbidden in (
                "expected_decision",
                "slice_tags",
                "case_id",
                "presentation_order",
                "rationale_id",
            ):
                assert forbidden not in rendered
            assert all(item.response == BlankResponse() for item in packet.items)

    def test_the_manifest_holds_the_key_and_not_the_answers(
        self, packet_set: PacketSet
    ) -> None:
        manifest = packet_set.manifest
        cases = {case.blinded_item_id: case for case in load_registered_cases()}

        assert manifest.handling == MANIFEST_HANDLING
        assert manifest.label_set_ref == "judge-calibration-expected-labels@1.0.0"
        assert manifest.blinding_plan_ref == "judge-calibration-blinding@1.0.0"
        rendered = manifest.model_dump_json()
        for case in cases.values():
            assert case.case_id in rendered
            assert case.expected_decision not in rendered.split('"')
        for key in manifest.packets:
            assert len(key.entries) == _ITEMS
            for entry in key.entries:
                assert entry.case_id == cases[entry.blinded_item_id].case_id
                assert entry.slice_tags == cases[entry.blinded_item_id].slice_tags

    def test_each_annotator_sees_one_order_and_the_set_sees_both(
        self, packet_set: PacketSet
    ) -> None:
        first, second = (
            {
                entry.blinded_item_id: entry.presentation_order
                for entry in packet_set.manifest.key_for(packet_id).entries
            }
            for packet_id in PACKET_IDS
        )
        pairwise = {item_id for item_id, order in first.items() if order is not None}

        assert len(pairwise) == _PAIRWISE_ITEMS
        for item_id in pairwise:
            assert {first[item_id], second[item_id]} == {"ab", "ba"}
        # Randomised, not assigned: neither packet is "the swapped one".
        assert len({first[item_id] for item_id in pairwise}) == 2

    def test_a_swapped_item_shows_the_two_excerpts_the_other_way_round(
        self, packet_set: PacketSet
    ) -> None:
        cases = {case.blinded_item_id: case for case in load_registered_cases()}
        swapped = 0
        for packet in packet_set.packets:
            entries = {
                entry.blinded_item_id: entry
                for entry in packet_set.manifest.key_for(packet.packet_id).entries
            }
            for item in packet.items:
                case = cases[item.blinded_item_id]
                if entries[item.blinded_item_id].presentation_order != "ba":
                    assert item.material.report_excerpt == case.material.report_excerpt
                    continue
                swapped += 1
                assert item.material.report_excerpt == case.material.second_excerpt
                assert item.material.second_excerpt == case.material.report_excerpt
        assert swapped == _PAIRWISE_ITEMS


class TestDeterminism:
    def test_the_same_seed_renders_the_same_set(self) -> None:
        assert build_packet_set().model_dump_json() == build_packet_set().model_dump_json()

    def test_the_default_seed_is_the_registered_blinding_plan(
        self, packet_set: PacketSet
    ) -> None:
        plan = registered_blinding_plan()

        assert packet_set.seed == plan.seed
        assert packet_set.manifest.seed == plan.seed
        assert build_packet_set(seed=plan.seed).packet_set_id == packet_set.packet_set_id

    def test_another_seed_is_another_set(self, packet_set: PacketSet) -> None:
        other = build_packet_set(seed=7)

        assert other.packet_set_id != packet_set.packet_set_id
        assert [item.blinded_item_id for item in other.packet("expert-a").items] != [
            item.blinded_item_id for item in packet_set.packet("expert-a").items
        ]

    def test_a_negative_seed_is_refused(self) -> None:
        with pytest.raises(ValueError, match="non-negative"):
            build_packet_set(seed=-1)

    def test_a_registry_root_without_a_blinding_plan_is_refused(
        self, tmp_path: Path
    ) -> None:
        source = (
            _ROOT
            / "eval_registry"
            / "content"
            / "calibration_guideline"
            / "judge-calibration-annotation-guide"
            / "1.0.0.json"
        )
        target = tmp_path / "content" / "blinding_plan" / "judge-calibration-blinding"
        target.mkdir(parents=True)
        (target / "1.0.0.json").write_text(
            source.read_text(encoding="utf-8"), encoding="utf-8"
        )

        with pytest.raises(ValueError, match="is not a blinding plan"):
            registered_blinding_plan(tmp_path)


class TestTheWrittenLayout:
    def test_the_key_is_written_outside_every_packet_directory(
        self, tmp_path: Path, packet_set: PacketSet
    ) -> None:
        paths = write_packet_set(tmp_path)
        base = tmp_path / packet_set.packet_set_id

        assert [path.relative_to(tmp_path).as_posix() for path in paths] == [
            f"{packet_set.packet_set_id}/expert-a/packet.json",
            f"{packet_set.packet_set_id}/expert-b/packet.json",
            f"{packet_set.packet_set_id}/manifest.json",
            f"{packet_set.packet_set_id}/README.md",
        ]
        for packet_id in PACKET_IDS:
            handed_over = sorted(
                path.name for path in (base / packet_id).iterdir()
            )
            assert handed_over == ["packet.json"]
            LabelPacket.model_validate_json(
                (base / packet_id / "packet.json").read_text(encoding="utf-8")
            )
        assert MANIFEST_HANDLING in (base / "manifest.json").read_text(encoding="utf-8")

    def test_the_readme_tells_the_steward_what_not_to_send(self, written: Path) -> None:
        readme = (written / "README.md").read_text(encoding="utf-8")

        assert "Send nothing else." in readme
        assert "`manifest.json` is the blinding key and stays with the" in readme
        assert "python -m src.calibration ingest" in readme
        assert "--manifest manifest.json" in readme

    def test_the_default_output_root_is_ignored_by_git(self) -> None:
        ignore = (_ROOT / ".gitignore").read_text(encoding="utf-8").splitlines()

        assert DEFAULT_OUTPUT_ROOT == _ROOT / "outputs" / "calibration"
        assert "outputs/" in ignore


class TestIngestingACompletedPacket:
    def test_the_report_counts_are_the_ones_the_registry_implies(
        self, written: Path, packet_set: PacketSet
    ) -> None:
        decisions, _ = _synthetic_decisions(packet_set, "expert-a")
        labels = _write(
            written / "returned.json", _completed_packet(packet_set, "expert-a", decisions)
        )

        report = ingest_labels(labels, written / "manifest.json")

        assert report.packet_set_id == packet_set.packet_set_id
        assert report.packet_id == "expert-a"
        assert report.annotator_id == "ann-expert1"
        assert report.seed == packet_set.seed
        assert report.abstention_policy == "excluded"
        assert report.labels_ingested == _ITEMS
        overall = report.overall
        assert (overall.items, overall.binary_items, overall.pairwise_items) == (
            _ITEMS,
            _BINARY_ITEMS,
            _PAIRWISE_ITEMS,
        )
        # One abstention removes an item from the 2x2; 15 + 8 remain.
        assert (overall.raw_agreement.numerator, overall.raw_agreement.denominator) == (21, 23)
        assert overall.phi == pytest.approx(97 / 120)
        assert (overall.annotator_positive.numerator, overall.annotator_positive.denominator) == (
            8,
            23,
        )
        assert (overall.reference_positive.numerator, overall.reference_positive.denominator) == (
            8,
            23,
        )
        assert (overall.false_pass.numerator, overall.false_pass.denominator) == (1, 15)
        assert (overall.false_fail.numerator, overall.false_fail.denominator) == (1, 8)
        assert (overall.abstention.numerator, overall.abstention.denominator) == (1, 24)
        assert (
            overall.unresolved_reference.numerator,
            overall.unresolved_reference.denominator,
        ) == (0, 24)
        assert (
            overall.exact_decision_match.numerator,
            overall.exact_decision_match.denominator,
        ) == (21, 23)
        assert (overall.pairwise_agreement.numerator, overall.pairwise_agreement.denominator) == (
            _PAIRWISE_ITEMS,
            _PAIRWISE_ITEMS,
        )
        assert overall.pairwise_non_decision.numerator == 0
        assert len(report.slices) == 15
        assert sum(entry.items for entry in report.slices) >= _ITEMS

    def test_every_published_rate_carries_its_denominator_and_interval(
        self, written: Path, packet_set: PacketSet
    ) -> None:
        decisions, _ = _synthetic_decisions(packet_set, "expert-a")
        labels = _write(
            written / "returned.json", _completed_packet(packet_set, "expert-a", decisions)
        )

        report = ingest_labels(labels, written / "manifest.json")

        for entry in (report.overall, *report.slices):
            for field in (
                "raw_agreement",
                "annotator_positive",
                "reference_positive",
                "exact_decision_match",
                "false_pass",
                "false_fail",
                "abstention",
                "unresolved_reference",
                "pairwise_agreement",
                "pairwise_non_decision",
            ):
                rate: RateSummary = getattr(entry, field)
                if rate.denominator == 0:
                    assert rate.rate is None and rate.interval_low is None
                    continue
                assert rate.rate == pytest.approx(rate.numerator / rate.denominator)
                assert rate.interval_low is not None and rate.interval_high is not None
                assert rate.interval_low <= rate.rate + 1e-9
                assert rate.rate <= rate.interval_high + 1e-9

    def test_a_compact_label_file_is_the_same_measurement(
        self, written: Path, packet_set: PacketSet
    ) -> None:
        decisions, _ = _synthetic_decisions(packet_set, "expert-b")
        packet_form = _write(
            written / "packet.json",
            _completed_packet(packet_set, "expert-b", decisions, annotator_id="ann-expert2"),
        )
        compact_form = _write(
            written / "compact.json", _label_file(packet_set, "expert-b", decisions)
        )

        from_packet = ingest_labels(packet_form, written / "manifest.json")
        from_compact = ingest_labels(compact_form, written / "manifest.json")

        assert from_compact.overall == from_packet.overall
        assert from_compact.slices == from_packet.slices
        assert from_compact.packet_id == "expert-b"

    def test_a_swapped_pairwise_answer_is_normalised_back_to_the_registry(
        self, written: Path, packet_set: PacketSet
    ) -> None:
        cases = {case.blinded_item_id: case for case in load_registered_cases()}
        for packet_id in PACKET_IDS:
            entries = {
                entry.blinded_item_id: entry
                for entry in packet_set.manifest.key_for(packet_id).entries
            }
            decisions = {
                item_id: (
                    {"first": "second", "second": "first"}[
                        cases[item_id].expected_decision
                    ]
                    if entry.presentation_order == "ba"
                    else cases[item_id].expected_decision
                )
                for item_id, entry in entries.items()
            }
            labels = _write(
                written / f"{packet_id}.json",
                _completed_packet(packet_set, packet_id, decisions),
            )

            report = ingest_labels(labels, written / "manifest.json")

            assert (
                report.overall.exact_decision_match.numerator,
                report.overall.exact_decision_match.denominator,
            ) == (_BINARY_ITEMS, _BINARY_ITEMS)
            assert report.overall.pairwise_agreement.numerator == _PAIRWISE_ITEMS

    def test_a_shown_order_answer_taken_at_face_value_would_be_wrong(
        self, written: Path, packet_set: PacketSet
    ) -> None:
        """The normalisation is load-bearing, not decoration."""
        cases = {case.blinded_item_id: case for case in load_registered_cases()}
        entries = {
            entry.blinded_item_id: entry
            for entry in packet_set.manifest.key_for("expert-a").entries
        }
        decisions = {
            item_id: cases[item_id].expected_decision for item_id in entries
        }
        swapped = sum(
            1
            for entry in entries.values()
            if entry.presentation_order == "ba"
        )
        labels = _write(
            written / "face-value.json", _completed_packet(packet_set, "expert-a", decisions)
        )

        report = ingest_labels(labels, written / "manifest.json")

        assert swapped > 0
        assert report.overall.pairwise_agreement.numerator == _PAIRWISE_ITEMS - swapped

    def test_the_markdown_never_prints_agreement_without_what_qualifies_it(
        self, written: Path, packet_set: PacketSet
    ) -> None:
        decisions, _ = _synthetic_decisions(packet_set, "expert-a")
        labels = _write(
            written / "returned.json", _completed_packet(packet_set, "expert-a", decisions)
        )

        rendered = render_report(ingest_labels(labels, written / "manifest.json"))

        assert "# Offline calibration label report" in rendered
        assert f"Packet set: `{packet_set.packet_set_id}`" in rendered
        assert "Abstention policy: `excluded`" in rendered
        agreement_rows = [
            line for line in rendered.splitlines() if line.startswith("| all | 24 |")
        ]
        assert len(agreement_rows) == 1
        row = agreement_rows[0]
        assert "+0.808" in row
        assert row.count("8/23") == 2  # both positive rates, beside φ
        assert "1/15" in row and "1/8" in row
        assert "95% Wilson interval" in rendered
        assert "Position bias is a judge measurement" in rendered
        assert "| ambiguous-comparative |" in rendered


class TestWhatIngestRefuses:
    @pytest.fixture()
    def manifest(self, written: Path) -> Path:
        return written / "manifest.json"

    def test_a_file_that_is_not_json(self, written: Path, manifest: Path) -> None:
        broken = written / "broken.json"
        broken.write_text("{not json", encoding="utf-8")

        with pytest.raises(ValueError, match="not valid JSON"):
            ingest_labels(broken, manifest)

    def test_a_file_that_is_not_an_object(self, written: Path, manifest: Path) -> None:
        with pytest.raises(ValueError, match="must be a JSON object"):
            ingest_labels(_write(written / "list.json", []), manifest)

    def test_a_partially_labelled_packet_names_the_blanks(
        self, written: Path, manifest: Path, packet_set: PacketSet
    ) -> None:
        decisions, _ = _synthetic_decisions(packet_set, "expert-a")
        payload = _completed_packet(packet_set, "expert-a", decisions)
        payload["items"][0]["response"] = None
        payload["items"][1]["response"]["rationale"] = "   "
        blank = {payload["items"][index]["blinded_item_id"] for index in (0, 1)}

        with pytest.raises(ValueError, match="only partially labelled; 2 unlabelled") as caught:
            ingest_labels(_write(written / "partial.json", payload), manifest)

        assert all(item_id in str(caught.value) for item_id in blank)

    def test_a_partially_filled_compact_file(
        self, written: Path, manifest: Path, packet_set: PacketSet
    ) -> None:
        decisions, _ = _synthetic_decisions(packet_set, "expert-a")
        payload = _label_file(packet_set, "expert-a", decisions)
        payload["labels"][3]["decision"] = ""

        with pytest.raises(ValueError, match="only partially labelled; 1 unlabelled"):
            ingest_labels(_write(written / "partial-compact.json", payload), manifest)

    def test_missing_and_unknown_items(
        self, written: Path, manifest: Path, packet_set: PacketSet
    ) -> None:
        decisions, _ = _synthetic_decisions(packet_set, "expert-a")
        payload = _label_file(packet_set, "expert-a", decisions)

        short = dict(payload, labels=payload["labels"][:-1])
        with pytest.raises(ValueError, match="coverage mismatch"):
            ingest_labels(_write(written / "short.json", short), manifest)

        stranger = dict(payload, labels=[dict(row) for row in payload["labels"]])
        stranger["labels"][0]["blinded_item_id"] = "itm-000000000000"
        with pytest.raises(ValueError, match="coverage mismatch"):
            ingest_labels(_write(written / "stranger.json", stranger), manifest)

    def test_a_duplicated_item(
        self, written: Path, manifest: Path, packet_set: PacketSet
    ) -> None:
        decisions, _ = _synthetic_decisions(packet_set, "expert-a")
        payload = _label_file(packet_set, "expert-a", decisions)
        payload["labels"] = [*payload["labels"], payload["labels"][0]]

        with pytest.raises(ValidationError, match="unique"):
            ingest_labels(_write(written / "duplicate.json", payload), manifest)

    def test_a_returned_packet_that_edited_its_material(
        self, written: Path, manifest: Path, packet_set: PacketSet
    ) -> None:
        decisions, _ = _synthetic_decisions(packet_set, "expert-a")
        payload = _completed_packet(packet_set, "expert-a", decisions)
        payload["items"][0]["material"]["report_excerpt"] = "tampered"

        with pytest.raises(ValueError, match="changed registered material"):
            ingest_labels(_write(written / "tampered.json", payload), manifest)

    def test_a_label_that_renames_its_own_type(
        self, written: Path, manifest: Path, packet_set: PacketSet
    ) -> None:
        decisions, _ = _synthetic_decisions(packet_set, "expert-a")
        payload = _label_file(packet_set, "expert-a", decisions)
        row = next(
            row for row in payload["labels"] if row["label_type"] == "claim_support"
        )
        row["label_type"] = "citation_correctness"
        row["decision"] = "correct"

        with pytest.raises(ValueError, match="does not match the registered"):
            ingest_labels(_write(written / "retyped.json", payload), manifest)

    def test_a_decision_outside_the_vocabulary(
        self, written: Path, manifest: Path, packet_set: PacketSet
    ) -> None:
        decisions, _ = _synthetic_decisions(packet_set, "expert-a")
        payload = _label_file(packet_set, "expert-a", decisions)
        payload["labels"][0]["decision"] = "looks_fine"

        with pytest.raises(ValidationError, match="is not valid for"):
            ingest_labels(_write(written / "vocab.json", payload), manifest)

    def test_a_manifest_that_is_not_a_manifest(
        self, written: Path, packet_set: PacketSet
    ) -> None:
        decisions, _ = _synthetic_decisions(packet_set, "expert-a")
        labels = _write(
            written / "returned.json", _completed_packet(packet_set, "expert-a", decisions)
        )
        not_a_manifest = _write(written / "nope.json", {"hello": "world"})

        with pytest.raises(ValueError, match="is not a packet manifest"):
            ingest_labels(labels, not_a_manifest)

    def test_a_manifest_that_no_longer_describes_the_registry(
        self, written: Path, packet_set: PacketSet
    ) -> None:
        decisions, _ = _synthetic_decisions(packet_set, "expert-a")
        labels = _write(
            written / "returned.json", _completed_packet(packet_set, "expert-a", decisions)
        )
        drifted = json.loads((written / "manifest.json").read_text(encoding="utf-8"))
        drifted["packet_set_id"] = "pkt-000000000000"

        with pytest.raises(ValueError, match="no longer describes this registry"):
            ingest_labels(labels, _write(written / "drifted.json", drifted))


class TestTheObjectsRefuseTheirOwnMisuse:
    def test_a_manifest_key_for_an_unknown_packet(self, packet_set: PacketSet) -> None:
        with pytest.raises(ValueError, match="is not a packet of set"):
            packet_set.manifest.key_for("expert-z")

    def test_a_packet_set_without_that_packet(self, packet_set: PacketSet) -> None:
        with pytest.raises(ValueError, match="is not a packet of set"):
            packet_set.packet("expert-z")

    def test_a_packet_item_whose_shape_contradicts_its_type(self) -> None:
        with pytest.raises(ValidationError, match="second_excerpt is required"):
            PacketItem(
                blinded_item_id="itm-000000000000",
                label_type=LabelType.PAIRWISE_PREFERENCE,
                material=PacketMaterial(report_excerpt="one"),
                allowed_decisions=decision_vocabulary(LabelType.PAIRWISE_PREFERENCE),
            )

    def test_a_packet_item_with_an_invented_vocabulary(self) -> None:
        with pytest.raises(ValidationError, match="allowed_decisions do not match"):
            PacketItem(
                blinded_item_id="itm-000000000000",
                label_type=LabelType.CLAIM_SUPPORT,
                material=PacketMaterial(report_excerpt="one"),
                allowed_decisions=("fine", "not fine"),
            )

    def test_a_packet_with_repeated_items(self, packet_set: PacketSet) -> None:
        item = packet_set.packet("expert-a").items[0]

        with pytest.raises(ValidationError, match="unique"):
            LabelPacket(packet_id="expert-a", instructions=INSTRUCTIONS, items=(item, item))

    def test_a_manifest_entry_that_records_an_order_it_cannot_have(self) -> None:
        with pytest.raises(ValidationError, match="presentation_order is recorded only"):
            ManifestEntry(
                position=1,
                blinded_item_id="itm-000000000000",
                case_id="case",
                label_type=LabelType.CLAIM_SUPPORT,
                slice_tags=("baseline-easy",),
                presentation_order="ab",
            )

    def test_a_key_whose_positions_have_a_gap(self) -> None:
        def entry(position: int, suffix: str) -> ManifestEntry:
            return ManifestEntry(
                position=position,
                blinded_item_id=f"itm-00000000000{suffix}",
                case_id=f"case-{suffix}",
                label_type=LabelType.CLAIM_SUPPORT,
                slice_tags=("baseline-easy",),
            )

        with pytest.raises(ValidationError, match="contiguous from 1"):
            PacketKey(packet_id="expert-a", entries=(entry(1, "0"), entry(3, "1")))

        with pytest.raises(ValidationError, match="unique"):
            PacketKey(packet_id="expert-a", entries=(entry(1, "0"), entry(2, "0")))

    def test_a_manifest_whose_packets_cover_different_items(
        self, packet_set: PacketSet
    ) -> None:
        first, second = packet_set.manifest.packets
        trimmed = PacketKey(
            packet_id=second.packet_id,
            entries=tuple(
                entry.model_copy(update={"position": index})
                for index, entry in enumerate(second.entries[:-1], start=1)
            ),
        )

        with pytest.raises(ValidationError, match="must cover the same items"):
            PacketManifest(
                packet_set_id=packet_set.packet_set_id,
                seed=packet_set.seed,
                label_set_ref=packet_set.manifest.label_set_ref,
                blinding_plan_ref=packet_set.manifest.blinding_plan_ref,
                handling=MANIFEST_HANDLING,
                packets=(first, trimmed),
            )

    def test_a_manifest_that_names_the_wrong_slots(self, packet_set: PacketSet) -> None:
        first = packet_set.manifest.packets[0]

        with pytest.raises(ValidationError, match="describes exactly"):
            PacketManifest(
                packet_set_id=packet_set.packet_set_id,
                seed=packet_set.seed,
                label_set_ref=packet_set.manifest.label_set_ref,
                blinding_plan_ref=packet_set.manifest.blinding_plan_ref,
                handling=MANIFEST_HANDLING,
                packets=(first,),
            )

    def test_a_packet_set_whose_key_belongs_to_another_set(
        self, packet_set: PacketSet
    ) -> None:
        with pytest.raises(ValidationError, match="different packet set"):
            PacketSet(
                packet_set_id="pkt-000000000000",
                seed=packet_set.seed,
                packets=packet_set.packets,
                manifest=packet_set.manifest,
            )

    def test_a_packet_set_that_disagrees_with_its_key_about_the_seed(
        self, packet_set: PacketSet
    ) -> None:
        with pytest.raises(ValidationError, match="seed differs"):
            PacketSet(
                packet_set_id=packet_set.packet_set_id,
                seed=packet_set.seed + 1,
                packets=packet_set.packets,
                manifest=packet_set.manifest,
            )

    def test_a_packet_set_missing_a_slot(self, packet_set: PacketSet) -> None:
        with pytest.raises(ValidationError, match="contains exactly"):
            PacketSet(
                packet_set_id=packet_set.packet_set_id,
                seed=packet_set.seed,
                packets=(packet_set.packets[0],),
                manifest=packet_set.manifest,
            )

    def test_a_completed_item_answering_outside_its_vocabulary(self) -> None:
        with pytest.raises(ValidationError, match="outside the vocabulary"):
            CompletedPacketItem(
                blinded_item_id="itm-000000000000",
                label_type=LabelType.CLAIM_SUPPORT,
                material=PacketMaterial(report_excerpt="one"),
                allowed_decisions=decision_vocabulary(LabelType.CLAIM_SUPPORT),
                response=CompletedResponse(
                    decision="covered",
                    confidence=Confidence.HIGH,
                    rationale="wrong family",
                ),
            )

    def test_a_completed_item_with_an_invented_vocabulary(self) -> None:
        with pytest.raises(ValidationError, match="allowed_decisions do not match"):
            CompletedPacketItem(
                blinded_item_id="itm-000000000000",
                label_type=LabelType.CLAIM_SUPPORT,
                material=PacketMaterial(report_excerpt="one"),
                allowed_decisions=("fine",),
                response=CompletedResponse(
                    decision="fine", confidence=Confidence.HIGH, rationale="no"
                ),
            )

    def test_a_submitted_label_outside_its_vocabulary(self) -> None:
        with pytest.raises(ValidationError, match="is not valid for"):
            SubmittedLabel(
                blinded_item_id="itm-000000000000",
                label_type=LabelType.CLAIM_SUPPORT,
                decision="covered",
                confidence=Confidence.HIGH,
                rationale="wrong family",
            )

    def test_a_rate_whose_interval_went_missing(self) -> None:
        with pytest.raises(ValidationError, match="present or absent together"):
            RateSummary(
                numerator=1, denominator=2, rate=0.5, interval_low=None, interval_high=None
            )

        with pytest.raises(ValidationError, match="two bounds or none"):
            RateSummary(
                numerator=1, denominator=2, rate=0.5, interval_low=0.1, interval_high=None
            )


class TestTheCommandLine:
    def test_packets_then_ingest_is_the_whole_workflow(
        self, tmp_path: Path, packet_set: PacketSet, capsys: pytest.CaptureFixture[str]
    ) -> None:
        assert main(["packets", "--output", str(tmp_path)]) == 0
        written = capsys.readouterr().out.splitlines()
        base = tmp_path / packet_set.packet_set_id
        assert written[0] == str(base / "expert-a" / "packet.json")
        assert written[2] == str(base / "manifest.json")

        decisions, _ = _synthetic_decisions(packet_set, "expert-a")
        labels = _write(
            tmp_path / "returned.json", _completed_packet(packet_set, "expert-a", decisions)
        )
        assert main(["ingest", str(labels), "--manifest", str(base / "manifest.json")]) == 0
        stdout = capsys.readouterr().out
        assert "# Offline calibration label report" in stdout
        assert "| all | 24 | 21/23" in stdout

        report_path = tmp_path / "reports" / "agreement.md"
        assert (
            main(
                [
                    "ingest",
                    str(labels),
                    "--manifest",
                    str(base / "manifest.json"),
                    "--output",
                    str(report_path),
                ]
            )
            == 0
        )
        assert report_path.read_text(encoding="utf-8").startswith(
            "# Offline calibration label report"
        )

    def test_a_seed_flag_moves_the_whole_set(self, tmp_path: Path) -> None:
        assert main(["packets", "--output", str(tmp_path), "--seed", "99"]) == 0

        assert [path.name for path in tmp_path.iterdir()] == [
            build_packet_set(seed=99).packet_set_id
        ]

    def test_a_refused_input_exits_two_and_says_why(
        self, tmp_path: Path, capsys: pytest.CaptureFixture[str]
    ) -> None:
        assert main(["packets", "--output", str(tmp_path)]) == 0
        capsys.readouterr()
        base = next(path for path in tmp_path.iterdir() if path.is_dir())
        malformed = tmp_path / "malformed.json"
        malformed.write_text("[]", encoding="utf-8")

        assert (
            main(["ingest", str(malformed), "--manifest", str(base / "manifest.json")]) == 2
        )
        assert "calibration input refused" in capsys.readouterr().err


class TestTheProtocolDocumentDescribesThisWorkflow:
    def test_the_commands_in_the_document_are_the_commands_that_exist(
        self, doc: str
    ) -> None:
        assert "python -m src.calibration packets" in doc
        assert "python -m src.calibration ingest" in doc
        assert "--manifest" in doc
        assert "--seed" in doc

    def test_the_documented_layout_is_the_layout_written(
        self, doc: str, written: Path, packet_set: PacketSet
    ) -> None:
        for line in (
            "outputs/calibration/<packet_set_id>/expert-a/packet.json",
            "outputs/calibration/<packet_set_id>/expert-b/packet.json",
            "outputs/calibration/<packet_set_id>/manifest.json",
        ):
            assert line in doc
        assert (written / "expert-a" / "packet.json").is_file()
        assert (written / "expert-b" / "packet.json").is_file()
        assert (written / "manifest.json").is_file()
        assert packet_set.packet_set_id.startswith("pkt-")

    def test_the_document_states_the_default_seed_the_module_uses(self, doc: str) -> None:
        assert f"seed `{registered_blinding_plan().seed}`" in doc

    def test_the_document_still_says_no_campaign_has_started(self, doc: str) -> None:
        assert "No human-labeling campaign has started." in doc
        assert "starts no labeling campaign" in doc
