"""The licensing posture and the status queue, asserted as behaviour.

WO-W15 acceptance criteria 1, 2 and 5 are all of the form "the rule is in
code, not in prose". These tests are the evidence: each one takes a
manifest that breaks exactly one rule and shows it does not load.

Mutation-checked: deleting the `L1_ARXIV_ABS_ONLY` block from
`Entry._posture` fails `test_a_pdf_link_is_refused`; deleting the
`S1_REVIEW_REQUIRED` block fails
`test_approved_without_a_reviewer_is_refused`; relaxing `extra="forbid"`
on `_Strict` fails `test_a_full_text_field_cannot_be_smuggled_in`.
"""

from __future__ import annotations

import copy
import json
from pathlib import Path
from typing import Any

import pytest

from src.content import loader, schema
from src.content.loader import default_content_root, load_path_dir
from src.content.schema import (
    FORBIDDEN_FIELD_NAMES,
    MANIFEST_MODELS,
    ContentValidationError,
    parse_briefing,
    parse_manifest,
    rehosting_fields,
)

pytestmark = pytest.mark.unit


# --------------------------------------------------------------------------
# Builders. One valid document, mutated per test, so every failure names a
# single deliberate difference from something that works.
# --------------------------------------------------------------------------


def _paper_entry(**overrides: Any) -> dict[str, Any]:
    entry: dict[str, Any] = {
        "position": 1,
        "resource_id": "arxiv:1706.03762",
        "kind": "paper",
        "title": "Attention Is All You Need",
        "authors": ["Ashish Vaswani"],
        "author_count": 8,
        "year": 2017,
        "canonical_url": "https://arxiv.org/abs/1706.03762",
        "license_note": "Link out to the arXiv abs page.",
        "attribution": "Vaswani et al. (arXiv.org)",
        "provenance": "curated",
        "status": "proposed",
        "rationale": "A rationale long enough to be a sentence.",
        "vocabulary": ["self-attention"],
        "est_minutes": 90,
        "sequencing": {"method": "editorial", "cites": []},
    }
    entry.update(overrides)
    return entry


def _manifest(**overrides: Any) -> dict[str, Any]:
    document: dict[str, Any] = {
        "manifest_version": 1,
        "path_id": "test-path",
        "kind": "flagship",
        "title": "Test path",
        "goal": "Prove the schema refuses what it says it refuses.",
        "version": 1,
        "status": "proposed",
        "updated_at": "2026-08-30",
        "fixture": False,
        "licensing": {
            "posture_id": "W-OD-3",
            "full_text": "link-out-only",
            "abstracts": "displayed-with-attribution",
            "quotes": "sparing-and-attributed",
            "s2_derived_facts": "link-back-required",
            "commercial_use": "none-through-phase-w",
            "counsel_confirmed": False,
            "source": "planning/07-learning-platform/02-CONTENT.md#22-papers",
        },
        "review": {
            "owner": "kudratsingh",
            "decisions": ["W-OD-3"],
            "curation_minutes_per_entry": 10,
        },
        "entries": [_paper_entry()],
    }
    document.update(overrides)
    return document


def _briefing(header: dict[str, Any] | None = None, body: str | None = None) -> str:
    head: dict[str, Any] = {
        "resource_id": "arxiv:1706.03762",
        "path_id": "test-path",
        "provenance": "generated",
        "label": "generated, human-reviewed",
        "briefing_version": 1,
        "generated_by": "job-abc123",
        "generated_at": "2026-08-30",
        "reviewed_by": "kudratsingh",
        "reviewed_at": "2026-08-30",
    }
    if header is not None:
        head.update(header)
    text = body if body is not None else (
        "> **Generated by the learning agent, reviewed by kudratsingh.**\n\n"
        "Body prose that says something about the paper.\n"
    )
    return f"<!-- provenance\n{json.dumps(head, indent=2)}\n-->\n\n{text}"


def _rule_of(exc: pytest.ExceptionInfo[ContentValidationError]) -> str:
    return exc.value.rule


# --------------------------------------------------------------------------
# c2 — the licensing posture, enforced.
# --------------------------------------------------------------------------


class TestLicensingPosture:
    def test_the_baseline_document_loads(self) -> None:
        """Guards the negative tests: they must differ by one thing only."""
        assert parse_manifest(_manifest()).path_id == "test-path"

    def test_a_pdf_link_is_refused(self) -> None:
        document = _manifest(
            entries=[
                _paper_entry(canonical_url="https://arxiv.org/pdf/1706.03762")
            ]
        )
        with pytest.raises(ContentValidationError) as exc:
            parse_manifest(document)
        assert _rule_of(exc) == schema.RULE_NO_FILE_URLS

    @pytest.mark.parametrize(
        "url",
        [
            "https://example.com/papers/attention.pdf",
            "https://arxiv.org/ftp/arxiv/papers/1706/1706.03762",
            "https://arxiv.org/e-print/1706.03762",
        ],
    )
    def test_every_file_shaped_url_is_refused(self, url: str) -> None:
        document = _manifest(entries=[_paper_entry(canonical_url=url)])
        with pytest.raises(ContentValidationError) as exc:
            parse_manifest(document)
        assert _rule_of(exc) == schema.RULE_NO_FILE_URLS

    def test_a_non_arxiv_paper_link_is_refused(self) -> None:
        """A mirror is not the abs page, however convenient it looks."""
        document = _manifest(
            entries=[
                _paper_entry(
                    canonical_url="https://www.semanticscholar.org/paper/abc",
                    resource_id="arxiv:1706.03762",
                )
            ]
        )
        with pytest.raises(ContentValidationError) as exc:
            parse_manifest(document)
        assert _rule_of(exc) == schema.RULE_ARXIV_ABS_ONLY

    def test_a_full_text_field_cannot_be_smuggled_in(self) -> None:
        document = _manifest(
            entries=[_paper_entry(full_text="the entire paper, pasted in")]
        )
        with pytest.raises(ContentValidationError) as exc:
            parse_manifest(document)
        assert _rule_of(exc) == schema.RULE_SCHEMA
        assert "full_text" in str(exc.value)

    def test_no_manifest_model_has_a_rehosting_field(self) -> None:
        """`L3` is a claim about the schema's shape, checked on the shape."""
        assert rehosting_fields(*MANIFEST_MODELS) == set()
        # And the list it is checked against is not empty, which would
        # make the assertion above vacuous.
        assert "full_text" in FORBIDDEN_FIELD_NAMES
        assert "pdf_url" in FORBIDDEN_FIELD_NAMES
        assert "transcript" in FORBIDDEN_FIELD_NAMES

    def test_an_abstract_without_attribution_is_refused(self) -> None:
        document = _manifest(
            entries=[
                _paper_entry(
                    abstract={
                        "text": "The dominant sequence transduction models...",
                        "url": "https://arxiv.org/abs/1706.03762",
                    }
                )
            ]
        )
        with pytest.raises(ContentValidationError) as exc:
            parse_manifest(document)
        assert _rule_of(exc) == schema.RULE_SCHEMA
        assert "source" in str(exc.value)

    def test_an_abstract_must_link_to_its_own_abs_page(self) -> None:
        document = _manifest(
            entries=[
                _paper_entry(
                    abstract={
                        "text": "An abstract belonging to a different paper.",
                        "source": "arXiv.org",
                        "url": "https://arxiv.org/abs/1810.04805",
                    }
                )
            ]
        )
        with pytest.raises(ContentValidationError) as exc:
            parse_manifest(document)
        assert _rule_of(exc) == schema.RULE_ABSTRACT_ATTRIBUTED

    def test_an_attributed_abstract_loads(self) -> None:
        document = _manifest(
            entries=[
                _paper_entry(
                    abstract={
                        "text": "An abstract, quoted with its attribution.",
                        "source": "arXiv.org (CC0 metadata)",
                        "url": "https://arxiv.org/abs/1706.03762",
                    }
                )
            ]
        )
        manifest = parse_manifest(document)
        assert manifest.entries[0].abstract is not None
        assert manifest.entries[0].abstract.source.startswith("arXiv.org")

    def test_a_citation_ancestry_claim_must_link_back_to_s2(self) -> None:
        document = _manifest(
            entries=[
                _paper_entry(
                    position=1,
                    resource_id="arxiv:1409.3215",
                    canonical_url="https://arxiv.org/abs/1409.3215",
                    sequencing={"method": "citation_ancestry", "cites": []},
                )
            ]
        )
        with pytest.raises(ContentValidationError) as exc:
            parse_manifest(document)
        assert _rule_of(exc) == schema.RULE_S2_LINKS_BACK

    def test_a_link_back_must_actually_point_at_s2(self) -> None:
        document = _manifest(
            entries=[
                _paper_entry(),
                _paper_entry(
                    position=2,
                    resource_id="arxiv:1810.04805",
                    canonical_url="https://arxiv.org/abs/1810.04805",
                    sequencing={
                        "method": "citation_ancestry",
                        "cites": ["arxiv:1706.03762"],
                        "evidence_url": "https://example.com/i-promise",
                    },
                ),
            ]
        )
        with pytest.raises(ContentValidationError) as exc:
            parse_manifest(document)
        assert _rule_of(exc) == schema.RULE_S2_LINKS_BACK

    def test_youtube_is_refused_wherever_it_appears(self) -> None:
        """`L7` — the 30-day metadata clock a git file cannot honour."""
        document = _manifest(
            entries=[
                _paper_entry(
                    kind="external_course",
                    resource_id="ext:some-video",
                    canonical_url="https://www.youtube.com/watch?v=abcdefghijk",
                )
            ]
        )
        with pytest.raises(ContentValidationError) as exc:
            parse_manifest(document)
        assert _rule_of(exc) == schema.RULE_NO_YOUTUBE

    def test_the_video_kind_does_not_exist_in_phase_w(self) -> None:
        document = _manifest(entries=[_paper_entry(kind="video")])
        with pytest.raises(ContentValidationError):
            parse_manifest(document)

    def test_a_copyleft_link_out_must_name_its_licence_url(self) -> None:
        document = _manifest(
            entries=[
                _paper_entry(
                    kind="external_course",
                    resource_id="ext:ocw-thing",
                    canonical_url="https://ocw.mit.edu/courses/some-course/",
                    license_id="CC BY-NC-SA-4.0",
                )
            ]
        )
        with pytest.raises(ContentValidationError) as exc:
            parse_manifest(document)
        assert _rule_of(exc) == schema.RULE_NONCOMMERCIAL

    @pytest.mark.parametrize(
        "field,value",
        [
            ("full_text", "we-host-it-now"),
            ("commercial_use", "allowed"),
            ("s2_derived_facts", "no-link-needed"),
        ],
    )
    def test_the_posture_block_admits_exactly_one_value_per_field(
        self, field: str, value: str
    ) -> None:
        """W-OD-3 is an assertion the manifest makes, not a knob."""
        document = _manifest()
        document["licensing"][field] = value
        with pytest.raises(ContentValidationError):
            parse_manifest(document)

    def test_the_resource_id_must_agree_with_the_link(self) -> None:
        document = _manifest(entries=[_paper_entry(resource_id="arxiv:1810.04805")])
        with pytest.raises(ContentValidationError) as exc:
            parse_manifest(document)
        assert _rule_of(exc) == schema.RULE_ID_MATCHES_URL


# --------------------------------------------------------------------------
# c1 / c5 — the status queue and the review gate.
# --------------------------------------------------------------------------


class TestStatusQueue:
    def test_approved_without_a_reviewer_is_refused(self) -> None:
        document = _manifest(
            entries=[
                _paper_entry(
                    status="approved",
                    briefing_file="briefings/x.md",
                    briefing_provenance="generated",
                )
            ]
        )
        with pytest.raises(ContentValidationError) as exc:
            parse_manifest(document)
        assert _rule_of(exc) == schema.RULE_REVIEW_REQUIRED

    def test_approved_with_an_empty_reviewer_is_refused(self) -> None:
        document = _manifest(
            entries=[
                _paper_entry(
                    status="approved",
                    reviewed_by="",
                    reviewed_at="2026-08-30",
                    briefing_file="briefings/x.md",
                    briefing_provenance="generated",
                )
            ]
        )
        with pytest.raises(ContentValidationError) as exc:
            parse_manifest(document)
        assert _rule_of(exc) == schema.RULE_REVIEW_REQUIRED

    def test_an_approved_paper_must_name_its_briefing(self) -> None:
        document = _manifest(
            entries=[
                _paper_entry(
                    status="approved",
                    reviewed_by="kudratsingh",
                    reviewed_at="2026-08-30",
                )
            ]
        )
        with pytest.raises(ContentValidationError) as exc:
            parse_manifest(document)
        assert _rule_of(exc) == schema.RULE_BRIEFING_REQUIRED

    def test_proposed_entries_are_not_servable(self) -> None:
        manifest = parse_manifest(_manifest())
        assert manifest.entries[0].status == "proposed"
        assert manifest.servable_entries == []

    @pytest.mark.parametrize("status", ["stale", "rejected"])
    def test_withdrawn_entries_are_not_servable(self, status: str) -> None:
        """Neither is "above published"; both must vanish from the API."""
        extra: dict[str, Any] = {"status": status}
        if status == "rejected":
            extra["rejection_reason"] = "Superseded by a better entry."
        manifest = parse_manifest(_manifest(entries=[_paper_entry(**extra)]))
        assert manifest.servable_entries == []

    def test_a_rejection_must_carry_its_reason(self) -> None:
        document = _manifest(entries=[_paper_entry(status="rejected")])
        with pytest.raises(ContentValidationError) as exc:
            parse_manifest(document)
        assert _rule_of(exc) == schema.RULE_REVIEW_REQUIRED

    def test_a_reason_without_a_rejection_is_refused(self) -> None:
        document = _manifest(
            entries=[_paper_entry(rejection_reason="but it is still proposed")]
        )
        with pytest.raises(ContentValidationError) as exc:
            parse_manifest(document)
        assert _rule_of(exc) == schema.RULE_REVIEW_REQUIRED

    def test_a_published_path_cannot_contain_an_entry_still_in_the_queue(
        self,
    ) -> None:
        document = _manifest(status="published")
        with pytest.raises(ContentValidationError) as exc:
            parse_manifest(document)
        assert _rule_of(exc) == schema.RULE_PATH_PUBLISH_GATE

    def test_a_published_path_may_carry_a_row_that_went_stale(self) -> None:
        """`02` §3.3 flags the path for repair; it does not unpublish it."""
        stale = _paper_entry(
            position=2,
            resource_id="arxiv:1810.04805",
            canonical_url="https://arxiv.org/abs/1810.04805",
            status="stale",
            staleness_note="Link stopped resolving on 2026-08-30.",
        )
        live = _paper_entry(
            status="published",
            reviewed_by="kudratsingh",
            reviewed_at="2026-08-30",
            briefing_file="briefings/x.md",
            briefing_provenance="generated",
        )
        manifest = parse_manifest(
            _manifest(status="published", entries=[live, stale])
        )
        assert [e.resource_id for e in manifest.servable_entries] == [
            "arxiv:1706.03762"
        ]

    def test_a_published_path_must_publish_something(self) -> None:
        stale = _paper_entry(status="stale")
        with pytest.raises(ContentValidationError) as exc:
            parse_manifest(_manifest(status="published", entries=[stale]))
        assert _rule_of(exc) == schema.RULE_PATH_PUBLISH_GATE

    def test_positions_must_be_contiguous(self) -> None:
        document = _manifest(
            entries=[_paper_entry(position=1), _paper_entry(position=3,
                resource_id="arxiv:1810.04805",
                canonical_url="https://arxiv.org/abs/1810.04805")]
        )
        with pytest.raises(ContentValidationError) as exc:
            parse_manifest(document)
        assert _rule_of(exc) == schema.RULE_POSITIONS_CONTIGUOUS

    def test_a_resource_may_appear_once_per_path(self) -> None:
        document = _manifest(
            entries=[_paper_entry(position=1), _paper_entry(position=2)]
        )
        with pytest.raises(ContentValidationError) as exc:
            parse_manifest(document)
        assert _rule_of(exc) == schema.RULE_UNIQUE_RESOURCE_IDS

    def test_a_cited_entry_must_come_earlier(self) -> None:
        """`02` §2.2: a paper cited by the others comes first."""
        document = _manifest(
            entries=[
                _paper_entry(
                    position=1,
                    sequencing={
                        "method": "citation_ancestry",
                        "cites": ["arxiv:1810.04805"],
                        "evidence_url": "https://api.semanticscholar.org/arXiv:1706.03762",
                    },
                ),
                _paper_entry(
                    position=2,
                    resource_id="arxiv:1810.04805",
                    canonical_url="https://arxiv.org/abs/1810.04805",
                ),
            ]
        )
        with pytest.raises(ContentValidationError) as exc:
            parse_manifest(document)
        assert _rule_of(exc) == schema.RULE_S2_LINKS_BACK

    def test_every_entry_carries_a_one_line_rationale(self) -> None:
        document = _manifest(entries=[_paper_entry(rationale="short")])
        with pytest.raises(ContentValidationError):
            parse_manifest(document)
        document = _manifest(entries=[_paper_entry(rationale="a\nb" * 20)])
        with pytest.raises(ContentValidationError) as exc:
            parse_manifest(document)
        assert _rule_of(exc) == schema.RULE_RATIONALE_PRESENT

    def test_a_briefing_may_not_be_labelled_curated(self) -> None:
        document = _manifest(
            entries=[
                _paper_entry(
                    briefing_file="briefings/x.md", briefing_provenance="curated"
                )
            ]
        )
        with pytest.raises(ContentValidationError) as exc:
            parse_manifest(document)
        assert _rule_of(exc) == schema.RULE_BRIEFING_REQUIRED

    def test_author_count_cannot_understate_the_listed_authors(self) -> None:
        document = _manifest(
            entries=[_paper_entry(authors=["A", "B", "C"], author_count=2)]
        )
        with pytest.raises(ContentValidationError):
            parse_manifest(document)


# --------------------------------------------------------------------------
# c5 — provenance headers, per file.
# --------------------------------------------------------------------------


class TestBriefingProvenance:
    def test_a_valid_briefing_parses(self) -> None:
        briefing = parse_briefing(_briefing())
        assert briefing.header.generated_by == "job-abc123"
        assert briefing.body.startswith("> **Generated by the learning agent")

    def test_a_briefing_without_a_header_is_refused(self) -> None:
        with pytest.raises(ContentValidationError) as exc:
            parse_briefing("# Just a markdown file\n")
        assert _rule_of(exc) == schema.RULE_BRIEFING_REQUIRED

    def test_a_generated_briefing_must_name_its_run(self) -> None:
        with pytest.raises(ContentValidationError) as exc:
            parse_briefing(_briefing({"generated_by": None}))
        assert _rule_of(exc) == schema.RULE_GENERATED_NEEDS_RUN

    def test_the_generated_label_is_fixed_by_02(self) -> None:
        with pytest.raises(ContentValidationError) as exc:
            parse_briefing(_briefing({"label": "written by a human, honest"}))
        assert _rule_of(exc) == schema.RULE_GENERATED_NEEDS_RUN

    def test_the_display_label_must_be_the_first_visible_line(self) -> None:
        text = _briefing(body="Straight into the prose, no label anywhere.\n")
        with pytest.raises(ContentValidationError) as exc:
            schema.check_display_label(parse_briefing(text))
        assert _rule_of(exc) == schema.RULE_GENERATED_NEEDS_RUN

    def test_an_unattributed_block_quote_is_refused(self) -> None:
        text = _briefing(
            body=(
                "> **Generated by the learning agent, reviewed by kudratsingh.**\n\n"
                "As the paper says:\n\n"
                "> A sentence lifted straight out of the paper.\n\n"
                "And on we go.\n"
            )
        )
        with pytest.raises(ContentValidationError) as exc:
            schema.check_quotes(parse_briefing(text))
        assert _rule_of(exc) == schema.RULE_QUOTES_ATTRIBUTED

    def test_an_attributed_block_quote_passes(self) -> None:
        text = _briefing(
            body=(
                "> **Generated by the learning agent, reviewed by kudratsingh.**\n\n"
                "As the paper says:\n\n"
                "> A sentence lifted straight out of the paper.\n\n"
                "— Vaswani et al., https://arxiv.org/abs/1706.03762\n\n"
                "And on we go.\n"
            )
        )
        schema.check_quotes(parse_briefing(text))

    def test_quoting_too_much_is_refused_even_when_attributed(self) -> None:
        quote = "\n".join(f"> Quoted line number {i} of the paper." for i in range(60))
        text = _briefing(
            body=(
                "> **Generated by the learning agent, reviewed by kudratsingh.**\n\n"
                f"{quote}\n\n"
                "— Vaswani et al., https://arxiv.org/abs/1706.03762\n"
            )
        )
        with pytest.raises(ContentValidationError) as exc:
            schema.check_quotes(parse_briefing(text))
        assert _rule_of(exc) == schema.RULE_QUOTES_ATTRIBUTED

    @pytest.mark.parametrize(
        "url,rule",
        [
            ("https://arxiv.org/pdf/1706.03762", schema.RULE_NO_FILE_URLS),
            ("https://www.youtube.com/watch?v=abcdefghijk", schema.RULE_NO_YOUTUBE),
        ],
    )
    def test_a_briefing_may_not_link_to_a_file_or_a_video(
        self, url: str, rule: str
    ) -> None:
        text = _briefing(
            body=(
                "> **Generated by the learning agent, reviewed by kudratsingh.**\n\n"
                f"See {url} for the details.\n"
            )
        )
        with pytest.raises(ContentValidationError) as exc:
            schema.check_briefing_urls(parse_briefing(text))
        assert _rule_of(exc) == rule


# --------------------------------------------------------------------------
# The loader's cross-file gate — the half a single file cannot enforce.
# --------------------------------------------------------------------------


def _write_path(tmp_path: Path, document: dict[str, Any]) -> Path:
    directory = tmp_path / "paths" / document["path_id"]
    (directory / "briefings").mkdir(parents=True)
    (directory / "path.json").write_text(json.dumps(document), encoding="utf-8")
    return directory


class TestLoaderCrossChecks:
    def test_an_approved_entry_with_no_briefing_file_on_disk_fails(
        self, tmp_path: Path
    ) -> None:
        document = _manifest(
            entries=[
                _paper_entry(
                    status="approved",
                    reviewed_by="kudratsingh",
                    reviewed_at="2026-08-30",
                    briefing_file="briefings/missing.md",
                    briefing_provenance="generated",
                )
            ]
        )
        directory = _write_path(tmp_path, document)
        with pytest.raises(ContentValidationError) as exc:
            load_path_dir(directory)
        assert _rule_of(exc) == schema.RULE_BRIEFING_REQUIRED

    def test_a_briefing_claiming_a_reviewer_the_manifest_does_not_fails(
        self, tmp_path: Path
    ) -> None:
        """The forgery direction: a file that says it was reviewed."""
        document = _manifest(
            entries=[
                _paper_entry(
                    briefing_file="briefings/x.md", briefing_provenance="generated"
                )
            ]
        )
        directory = _write_path(tmp_path, document)
        (directory / "briefings" / "x.md").write_text(_briefing(), encoding="utf-8")
        with pytest.raises(ContentValidationError) as exc:
            load_path_dir(directory)
        assert _rule_of(exc) == schema.RULE_REVIEW_REQUIRED

    def test_an_undrafted_briefing_on_a_proposed_entry_is_fine(
        self, tmp_path: Path
    ) -> None:
        """The normal pre-campaign state: a target, not yet a file."""
        document = _manifest(
            entries=[
                _paper_entry(
                    briefing_file="briefings/not-yet.md",
                    briefing_provenance="generated",
                )
            ]
        )
        path = load_path_dir(_write_path(tmp_path, document))
        assert path.briefings == {}
        assert path.manifest.servable_entries == []

    def test_the_manifest_must_live_in_a_directory_named_for_it(
        self, tmp_path: Path
    ) -> None:
        document = _manifest()
        directory = _write_path(tmp_path, document)
        renamed = directory.parent / "some-other-name"
        directory.rename(renamed)
        with pytest.raises(ContentValidationError):
            load_path_dir(renamed)

    def test_a_fixture_path_must_carry_its_banner(self, tmp_path: Path) -> None:
        document = _manifest(path_id="fx-path", kind="fixture", fixture=True)
        with pytest.raises(ContentValidationError) as exc:
            parse_manifest(document)
        assert _rule_of(exc) == schema.RULE_FIXTURE_BANNER

    def test_a_real_path_may_not_carry_one(self) -> None:
        document = _manifest(banner="FIXTURE CONTENT, honest")
        with pytest.raises(ContentValidationError) as exc:
            parse_manifest(document)
        assert _rule_of(exc) == schema.RULE_FIXTURE_BANNER

    def test_a_fixture_briefing_may_not_wear_the_generated_label(self) -> None:
        document = _manifest(
            path_id="fx-path",
            kind="fixture",
            fixture=True,
            banner="FIXTURE CONTENT. Demo scaffolding.",
            entries=[
                _paper_entry(
                    briefing_file="briefings/x.md", briefing_provenance="generated"
                )
            ],
        )
        with pytest.raises(ContentValidationError) as exc:
            parse_manifest(document)
        assert _rule_of(exc) == schema.RULE_FIXTURE_BANNER


# --------------------------------------------------------------------------
# The manifests this PR actually ships.
# --------------------------------------------------------------------------


class TestShippedContent:
    @pytest.fixture(autouse=True)
    def _clear(self) -> None:
        loader.clear_cache()

    def test_every_shipped_path_loads(self) -> None:
        paths = loader.load_content_root(default_content_root())
        assert set(paths) == {"fixture-guided-read", "reading-first-papers"}

    def test_the_flagship_path_is_ten_papers_and_four_link_outs(self) -> None:
        manifest = loader.load_content_root(default_content_root())[
            "reading-first-papers"
        ].manifest
        kinds = [e.kind for e in manifest.entries]
        assert kinds.count("paper") == 10
        assert kinds.count("external_course") == 4

    def test_the_flagship_path_publishes_nothing_yet(self) -> None:
        """The honest pre-campaign state, and the reason W-OD-2 exists."""
        manifest = loader.load_content_root(default_content_root())[
            "reading-first-papers"
        ].manifest
        assert manifest.status == "proposed"
        assert manifest.servable_entries == []
        assert all(e.status == "proposed" for e in manifest.entries)

    def test_every_flagship_entry_carries_a_rationale_for_the_owner(self) -> None:
        manifest = loader.load_content_root(default_content_root())[
            "reading-first-papers"
        ].manifest
        for entry in manifest.entries:
            assert len(entry.rationale) >= 40, entry.resource_id
            assert "\n" not in entry.rationale

    def test_the_generation_campaign_is_declared_deferred(self) -> None:
        manifest = loader.load_content_root(default_content_root())[
            "reading-first-papers"
        ].manifest
        assert manifest.generation is not None
        assert manifest.generation.status == "deferred-awaiting-W-OD-2"
        assert manifest.generation.decision == "W-OD-2"
        assert manifest.generation.max_budget_usd > 0

    def test_no_briefing_has_been_generated(self) -> None:
        """The spend boundary, asserted on disk rather than promised."""
        path = loader.load_content_root(default_content_root())[
            "reading-first-papers"
        ]
        assert path.briefings == {}
        drafted = sorted(
            p.name for p in (path.directory / "briefings").glob("*.md")
        )
        assert drafted == ["TEMPLATE.md"]

    def test_the_briefing_template_is_a_valid_briefing(self) -> None:
        """A template that would not load is a trap for the campaign."""
        template = (
            default_content_root()
            / "paths"
            / "reading-first-papers"
            / "briefings"
            / "TEMPLATE.md"
        )
        briefing = parse_briefing(template.read_text(encoding="utf-8"))
        schema.check_display_label(briefing)
        schema.check_quotes(briefing)
        schema.check_briefing_urls(briefing)
        assert briefing.header.reviewed_by is None

    def test_the_fixture_path_is_the_only_published_one(self) -> None:
        published = [p.path_id for p in loader.published_paths(default_content_root())]
        assert published == ["fixture-guided-read"]

    def test_the_fixture_banner_names_itself_unmistakably(self) -> None:
        manifest = loader.load_content_root(default_content_root())[
            "fixture-guided-read"
        ].manifest
        assert manifest.banner is not None
        assert loader.FIXTURE_MARKER in manifest.banner
        assert "reading-first-papers" in manifest.banner

    def test_every_fixture_briefing_says_so_in_its_body(self) -> None:
        path = loader.load_content_root(default_content_root())[
            "fixture-guided-read"
        ]
        assert len(path.briefings) == 3
        for briefing in path.briefings.values():
            assert loader.FIXTURE_MARKER in briefing.body
            assert briefing.header.provenance == "authored"
            assert briefing.header.generated_by is None

    def test_no_shipped_link_is_a_pdf_or_a_video(self) -> None:
        """The posture, re-asserted over the bytes that ship."""
        root = default_content_root()
        for document in (root / "paths").glob("*/path.json"):
            raw = document.read_text(encoding="utf-8")
            assert "/pdf/" not in raw
            assert ".pdf" not in raw
            assert "youtube.com" not in raw
            assert "youtu.be" not in raw

    def test_the_content_tree_reaches_the_image(self) -> None:
        """The failure the schema cannot catch: right manifest, no files.

        `.dockerignore` strips `*.md` from the build context, which would
        take every briefing companion with it, and `content/` is not
        under `src/` so `COPY src ./src` does not carry it either. Both
        halves are text in files no Python test would otherwise reach.
        """
        root = default_content_root().parent
        dockerfile = (root / "Dockerfile").read_text(encoding="utf-8")
        ignore = (root / ".dockerignore").read_text(encoding="utf-8")
        assert "COPY content ./content" in dockerfile
        assert "!content/**/*.md" in ignore
        # And the negation has to come *after* the blanket rule, since
        # the last matching pattern wins.
        assert ignore.index("*.md\n") < ignore.index("!content/**/*.md")

    def test_the_shipped_manifests_survive_a_round_trip(self) -> None:
        """Nothing in the files depends on key order or on pydantic defaults."""
        root = default_content_root()
        for document in (root / "paths").glob("*/path.json"):
            payload = json.loads(document.read_text(encoding="utf-8"))
            manifest = parse_manifest(copy.deepcopy(payload))
            again = parse_manifest(manifest.model_dump(mode="json"))
            assert again == manifest
