"""`GET /learn/paths*` — the flag, the gate, and the posture on the wire.

The gate tests are the point. WO-W15 c1 says "the endpoints never serve a
non-approved entry", and the only convincing way to assert that is to
build a content tree that *contains* unapproved entries and show they do
not come back.

Mutation-checked: changing `_detail` to read `manifest.entries` instead
of `manifest.servable_entries` fails
`test_a_withdrawn_entry_never_reaches_the_wire`; deleting the
`_require_enabled()` call from either handler fails the flag tests.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest
from httpx import ASGITransport, AsyncClient

from src.api import create_app
from src.api.learn import (
    DISABLED_DETAIL,
    INVALID_DETAIL,
    PATH_NOT_FOUND_DETAIL,
)
from src.config import Settings
from src.content import loader

pytestmark = pytest.mark.unit


def _entry(position: int, resource_id: str, url: str, **overrides: Any) -> dict[str, Any]:
    entry: dict[str, Any] = {
        "position": position,
        "resource_id": resource_id,
        "kind": "paper",
        "title": f"Paper {position}",
        "authors": ["A Name"],
        "author_count": 9,
        "year": 2020,
        "canonical_url": url,
        "license_note": "Link out to the arXiv abs page.",
        "attribution": "Someone et al. (arXiv.org)",
        "provenance": "curated",
        "status": "proposed",
        "rationale": "A rationale long enough to read like a sentence.",
        "vocabulary": ["a term"],
        "est_minutes": 60,
        "sequencing": {"method": "editorial", "cites": []},
    }
    entry.update(overrides)
    return entry


def _published_entry(
    position: int,
    resource_id: str,
    url: str,
    *,
    briefing_provenance: str = "generated",
) -> dict[str, Any]:
    return _entry(
        position,
        resource_id,
        url,
        status="published",
        reviewed_by="kudratsingh",
        reviewed_at="2026-08-30",
        briefing_file=f"briefings/{position:02d}.md",
        briefing_provenance=briefing_provenance,
    )


def _briefing_text(
    resource_id: str, path_id: str, provenance: str = "generated"
) -> str:
    generated = provenance == "generated"
    header = {
        "resource_id": resource_id,
        "path_id": path_id,
        "provenance": provenance,
        "label": (
            "generated, human-reviewed" if generated else "authored scaffolding"
        ),
        "briefing_version": 1,
        "generated_by": "job-test" if generated else None,
        "generated_at": "2026-08-30" if generated else None,
        "reviewed_by": "kudratsingh",
        "reviewed_at": "2026-08-30",
    }
    label = (
        "> **Generated by the learning agent, reviewed by kudratsingh.**"
        if generated
        else "> **FIXTURE CONTENT — authored placeholder, reviewed by kudratsingh.**"
    )
    body = f"{label}\n\nWhy this paper, why now: because the test needs a body.\n"
    return f"<!-- provenance\n{json.dumps(header)}\n-->\n\n{body}"


def _licensing() -> dict[str, Any]:
    return {
        "posture_id": "W-OD-3",
        "full_text": "link-out-only",
        "abstracts": "displayed-with-attribution",
        "quotes": "sparing-and-attributed",
        "s2_derived_facts": "link-back-required",
        "commercial_use": "none-through-phase-w",
        "counsel_confirmed": False,
        "source": "planning/07-learning-platform/02-CONTENT.md#22-papers",
    }


def _manifest_document(**overrides: Any) -> dict[str, Any]:
    document: dict[str, Any] = {
        "manifest_version": 1,
        "path_id": "demo-path",
        "kind": "flagship",
        "title": "Demo path",
        "goal": "Serve something.",
        "version": 3,
        "status": "published",
        "updated_at": "2026-08-30",
        "fixture": False,
        "licensing": _licensing(),
        "review": {
            "owner": "kudratsingh",
            "decisions": ["W-OD-3"],
            "curation_minutes_per_entry": 5,
        },
        "entries": [
            _published_entry(1, "arxiv:1706.03762", "https://arxiv.org/abs/1706.03762"),
            _published_entry(2, "arxiv:1810.04805", "https://arxiv.org/abs/1810.04805"),
        ],
    }
    document.update(overrides)
    return document


def _fixture_document(**overrides: Any) -> dict[str, Any]:
    """The labeled fixture path: banner required, briefings authored."""
    document = _manifest_document(
        path_id="fixture-demo",
        kind="fixture",
        fixture=True,
        banner="FIXTURE CONTENT. Demo scaffolding, not a reading path.",
        entries=[
            _published_entry(
                1,
                "arxiv:1706.03762",
                "https://arxiv.org/abs/1706.03762",
                briefing_provenance="authored",
            )
        ],
    )
    document.update(overrides)
    return document


def _write_path(root: Path, document: dict[str, Any]) -> Path:
    directory = root / "paths" / document["path_id"]
    (directory / "briefings").mkdir(parents=True)
    (directory / "path.json").write_text(json.dumps(document), encoding="utf-8")
    for entry in document["entries"]:
        if not entry.get("briefing_file"):
            continue
        (directory / entry["briefing_file"]).write_text(
            _briefing_text(
                entry["resource_id"],
                document["path_id"],
                entry["briefing_provenance"],
            ),
            encoding="utf-8",
        )
    return directory


def _write_published_tree(root: Path) -> None:
    """One published path, plus one still `proposed` so it can be hidden.

    The proposed path is the honest state of the real flagship path
    until its campaign runs, so "an unpublished path is invisible" is
    tested against the shape that actually ships.
    """
    _write_path(root, _manifest_document())
    _write_path(root, _fixture_document())
    _write_path(
        root,
        _manifest_document(
            path_id="draft-path",
            title="Draft path",
            status="proposed",
            entries=[
                _entry(1, "arxiv:2005.14165", "https://arxiv.org/abs/2005.14165")
            ],
        ),
    )


@pytest.fixture
def content_tree(tmp_path: Path) -> Path:
    root = tmp_path / "content"
    _write_published_tree(root)
    return root


@pytest.fixture(autouse=True)
def _clear_cache() -> None:
    loader.clear_cache()


def _configure(
    monkeypatch: pytest.MonkeyPatch, *, enabled: bool, root: Path | None
) -> None:
    settings = Settings(
        enable_learn_content=enabled,
        learn_content_root=str(root) if root is not None else "",
    )
    monkeypatch.setattr("src.api.learn.settings", settings)
    monkeypatch.setattr("src.content.loader.settings", settings)
    loader.clear_cache()


def _client() -> AsyncClient:
    app = create_app(build_workflow=lambda: object())
    return AsyncClient(transport=ASGITransport(app=app), base_url="http://test")


class TestFlagGating:
    @pytest.mark.parametrize(
        "url", ["/learn/paths", "/learn/paths/demo-path"]
    )
    async def test_routes_exist_and_report_the_flag_honestly(
        self, monkeypatch: pytest.MonkeyPatch, content_tree: Path, url: str
    ) -> None:
        """SR-07: the web tier has no flags, so it has to be told."""
        _configure(monkeypatch, enabled=False, root=content_tree)
        async with _client() as client:
            response = await client.get(url)
        assert response.status_code == 404
        assert response.json()["detail"] == DISABLED_DETAIL

    async def test_the_flag_is_off_by_default(self) -> None:
        assert Settings().enable_learn_content is False


class TestListing:
    async def test_only_published_paths_are_listed(
        self, monkeypatch: pytest.MonkeyPatch, content_tree: Path
    ) -> None:
        _configure(monkeypatch, enabled=True, root=content_tree)
        async with _client() as client:
            response = await client.get("/learn/paths")
        assert response.status_code == 200
        paths = response.json()["paths"]
        assert [p["path_id"] for p in paths] == ["demo-path", "fixture-demo"]

    async def test_the_summary_carries_the_fixture_banner(
        self, monkeypatch: pytest.MonkeyPatch, content_tree: Path
    ) -> None:
        """c3: the banner is sourced from the manifest, not from the UI."""
        _configure(monkeypatch, enabled=True, root=content_tree)
        async with _client() as client:
            paths = (await client.get("/learn/paths")).json()["paths"]
        real, fixture = paths
        assert real["fixture"] is False
        assert real["banner"] is None
        assert real["entry_count"] == 2
        assert real["est_minutes_total"] == 120
        assert fixture["fixture"] is True
        assert fixture["banner"].startswith("FIXTURE CONTENT")

    async def test_an_empty_content_root_lists_nothing(
        self, monkeypatch: pytest.MonkeyPatch, tmp_path: Path
    ) -> None:
        """A deployment that publishes nothing says so, honestly."""
        _configure(monkeypatch, enabled=True, root=tmp_path / "empty")
        async with _client() as client:
            response = await client.get("/learn/paths")
        assert response.status_code == 200
        assert response.json() == {"paths": []}


class TestDetail:
    async def test_the_detail_carries_entries_and_briefings(
        self, monkeypatch: pytest.MonkeyPatch, content_tree: Path
    ) -> None:
        _configure(monkeypatch, enabled=True, root=content_tree)
        async with _client() as client:
            body = (await client.get("/learn/paths/demo-path")).json()
        assert [e["position"] for e in body["entries"]] == [1, 2]
        assert body["entries"][0]["briefing_markdown"].startswith(
            "> **Generated by the learning agent"
        )
        assert body["entries"][0]["canonical_url"] == (
            "https://arxiv.org/abs/1706.03762"
        )

    async def test_the_posture_travels_with_the_content(
        self, monkeypatch: pytest.MonkeyPatch, content_tree: Path
    ) -> None:
        """A posture the page cannot render is not a posture."""
        _configure(monkeypatch, enabled=True, root=content_tree)
        async with _client() as client:
            body = (await client.get("/learn/paths/demo-path")).json()
        assert body["licensing"] == {
            "posture_id": "W-OD-3",
            "full_text": "link-out-only",
            "abstracts": "displayed-with-attribution",
            "quotes": "sparing-and-attributed",
            "s2_derived_facts": "link-back-required",
            "commercial_use": "none-through-phase-w",
            "counsel_confirmed": False,
            "source": "planning/07-learning-platform/02-CONTENT.md#22-papers",
        }

    async def test_author_count_is_carried_so_et_al_is_earned(
        self, monkeypatch: pytest.MonkeyPatch, content_tree: Path
    ) -> None:
        _configure(monkeypatch, enabled=True, root=content_tree)
        async with _client() as client:
            body = (await client.get("/learn/paths/demo-path")).json()
        entry = body["entries"][0]
        assert entry["author_count"] == 9
        assert len(entry["authors"]) == 1

    async def test_an_unpublished_path_is_a_404_not_a_locked_row(
        self, monkeypatch: pytest.MonkeyPatch, content_tree: Path
    ) -> None:
        _configure(monkeypatch, enabled=True, root=content_tree)
        async with _client() as client:
            response = await client.get("/learn/paths/draft-path")
        assert response.status_code == 404
        assert response.json()["detail"] == PATH_NOT_FOUND_DETAIL

    async def test_an_unknown_path_is_the_same_404(
        self, monkeypatch: pytest.MonkeyPatch, content_tree: Path
    ) -> None:
        _configure(monkeypatch, enabled=True, root=content_tree)
        async with _client() as client:
            response = await client.get("/learn/paths/no-such-path")
        assert response.status_code == 404
        assert response.json()["detail"] == PATH_NOT_FOUND_DETAIL


class TestServingGate:
    async def test_a_withdrawn_entry_never_reaches_the_wire(
        self, monkeypatch: pytest.MonkeyPatch, tmp_path: Path
    ) -> None:
        """WO-W15 c1, at the boundary that matters.

        The published path holds a third entry that went `stale` — the
        post-publication case `02` §3.3 describes, where the path stays
        up and the row drops out. If `_detail` read `manifest.entries`
        instead of `servable_entries`, the dead row would ship.
        """
        root = tmp_path / "content"
        stale = _published_entry(
            3, "arxiv:2005.14165", "https://arxiv.org/abs/2005.14165"
        )
        stale["status"] = "stale"
        stale["staleness_note"] = "Link stopped resolving on 2026-08-30."
        _write_path(root, _manifest_document(entries=[*_manifest_document()["entries"], stale]))

        _configure(monkeypatch, enabled=True, root=root)
        async with _client() as client:
            body = (await client.get("/learn/paths/demo-path")).json()
        served = [e["resource_id"] for e in body["entries"]]
        assert served == ["arxiv:1706.03762", "arxiv:1810.04805"]
        assert "arxiv:2005.14165" not in json.dumps(body)

    async def test_a_path_awaiting_review_is_invisible(
        self, monkeypatch: pytest.MonkeyPatch, tmp_path: Path
    ) -> None:
        """An `approved`-but-not-published path is not half-served."""
        root = tmp_path / "content"
        entries = _manifest_document()["entries"]
        for entry in entries:
            entry["status"] = "approved"
        _write_path(root, _manifest_document(status="approved", entries=entries))
        _configure(monkeypatch, enabled=True, root=root)
        async with _client() as client:
            listing = await client.get("/learn/paths")
            detail = await client.get("/learn/paths/demo-path")
        assert listing.json() == {"paths": []}
        assert detail.status_code == 404

    async def test_no_response_body_contains_a_pdf_or_video_link(
        self, monkeypatch: pytest.MonkeyPatch, content_tree: Path
    ) -> None:
        """WO-W15 c2, asserted over the bytes a client actually receives."""
        _configure(monkeypatch, enabled=True, root=content_tree)
        async with _client() as client:
            listing = (await client.get("/learn/paths")).text
            detail = (await client.get("/learn/paths/demo-path")).text
        for payload in (listing, detail):
            assert "/pdf/" not in payload
            assert ".pdf" not in payload
            assert "youtube.com" not in payload
            assert "youtu.be" not in payload

    async def test_no_response_field_could_carry_full_text(
        self, monkeypatch: pytest.MonkeyPatch, content_tree: Path
    ) -> None:
        _configure(monkeypatch, enabled=True, root=content_tree)
        async with _client() as client:
            body = (await client.get("/learn/paths/demo-path")).json()
        for entry in body["entries"]:
            assert set(entry) & {
                "body",
                "full_text",
                "pdf_url",
                "transcript",
            } == set()


class TestBrokenContent:
    async def test_an_invalid_manifest_is_a_503_not_a_partial_answer(
        self, monkeypatch: pytest.MonkeyPatch, tmp_path: Path
    ) -> None:
        """Serving "the rest of it" is how a licensing rule stops applying."""
        root = tmp_path / "content"
        directory = root / "paths" / "demo-path"
        directory.mkdir(parents=True)
        (directory / "path.json").write_text("{ not json", encoding="utf-8")
        _configure(monkeypatch, enabled=True, root=root)
        async with _client() as client:
            response = await client.get("/learn/paths")
        assert response.status_code == 503
        assert response.json()["detail"] == INVALID_DETAIL


class TestShippedContentOverHttp:
    async def test_the_repo_shipped_fixture_path_serves(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """The zero-config demo path, end to end through the router."""
        _configure(monkeypatch, enabled=True, root=None)
        async with _client() as client:
            listing = (await client.get("/learn/paths")).json()
            assert [p["path_id"] for p in listing["paths"]] == [
                "fixture-guided-read"
            ]
            detail = (
                await client.get("/learn/paths/fixture-guided-read")
            ).json()
        assert detail["banner"].startswith("FIXTURE CONTENT")
        assert len(detail["entries"]) == 3
        for entry in detail["entries"]:
            assert "FIXTURE CONTENT" in entry["briefing_markdown"]

    async def test_the_real_flagship_path_is_not_served_yet(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Because no briefing has been generated, and it says so."""
        _configure(monkeypatch, enabled=True, root=None)
        async with _client() as client:
            response = await client.get("/learn/paths/reading-first-papers")
        assert response.status_code == 404
        assert response.json()["detail"] == PATH_NOT_FOUND_DETAIL
