import { createHash } from "node:crypto";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

import { expect, test } from "@playwright/test";
import type { Page } from "@playwright/test";

import {
  A11Y_HEIGHTS,
  RAIL_ABSENT_BELOW,
  openRailDrawer,
  waitForRailMode,
} from "./support/a11y";
import { THEMES } from "./support/axe";
import { settleForCapture } from "./support/capture";
import { fillComposer } from "./support/composer";
import { FIXTURES } from "./support/env";
import { interruptStream } from "./support/intercept";
import { STATES, readyLocator } from "./support/states";
import type { ReadyCondition, StateEntry } from "./support/states";

/**
 * WO-28 — the visual regression baselines.
 *
 * `00-DISCOVERY.md` listed "visual regression" among the missing quality
 * tiers. This file is that tier, and it is deliberately the smallest thing
 * that closes it: Playwright's own `toHaveScreenshot`, no new dependency, no
 * hosted service, no approval UI, and a committed PNG per render.
 *
 * WHAT IS COVERED, AND THE DEPTH LIMIT THAT COMES WITH IT.
 * Twelve renders × light/dark × 412/1440 = forty-eight snapshots. That is the
 * SLICE, not the matrix: `06-WORK-ORDERS.md` §4 has thirty-one rows, WO-27's
 * axe sweep walks twenty states at three widths in both themes, and a
 * screenshot at every one of those intersections would be a hundred and
 * twenty committed PNGs that a legitimate padding change invalidates in one
 * commit. `05-MIGRATION.md` §4.2 already lists visual-regression coverage
 * depth as an accepted residual risk; the entry recording it is
 * `docs/revamp/evidence/gate-4/residual-risks.md`, and criterion 3 is that
 * the limit is written down rather than discovered later.
 *
 * WHY THE ENGINE IS CHROMIUM AND ONLY CHROMIUM.
 * The same argument `playwright.config.ts` makes for `@axe`, `@cls` and
 * `@csp`, and it is stronger here than for any of them. Text rasterisation,
 * font hinting, scrollbar geometry and form-control metrics all differ
 * between Chromium, Gecko and WebKit — so a cross-engine snapshot set is
 * three sets of bytes that go stale independently and disagree for reasons
 * that are never product defects. Cross-engine rendering drift is exactly the
 * maintenance debt this work order is scoped to exclude. The engine limit is
 * not hidden: it is `@visual` in `CHROMIUM_ONLY`, and it is stated in
 * `e2e/README.md` and in the residual-risks entry.
 *
 * THE SAME ARGUMENT APPLIES TO THE PLATFORM, WHICH IS WHY IT IS IN THE PATH.
 * `playwright.config.ts` sets `snapshotPathTemplate` to include `{platform}`,
 * so this set lives under `e2e/__screenshots__/darwin/`. macOS and Linux
 * rasterise the same font at the same size differently; a single set shared
 * between them would fail on whichever host did not produce it, which is a
 * flaky gate rather than a strict one. A Linux set is generated by running
 * `e2e:visual:update` on Linux — see `e2e/README.md`, "Regenerating".
 *
 * A PLATFORM WITH NO COMMITTED SET **SKIPS**, LOUDLY, AND THAT IS THE HONEST
 * BEHAVIOUR. The `web-e2e` CI job runs `--project=chromium` on a Linux runner,
 * where `__screenshots__/linux/` does not exist because nobody has generated
 * and reviewed it. The three things that could happen there are: fail all
 * forty-eight for the absence of bytes nobody wrote (a red build that means
 * "no baseline", which is not a regression); let the runner write its own and
 * pass (a baseline the runner produced and immediately agreed with, which
 * proves nothing and is the worse of the two); or skip with a message naming
 * the command that would fix it. This file does the third, and
 * `no platform's baseline set is committed` below is the guard that stops the
 * skip from quietly becoming permanent everywhere. `--update-snapshots` turns
 * the skip off, because that IS the request to generate the set.
 *
 * DETERMINISM IS THE WHOLE PRODUCT HERE. A visual gate that goes red for
 * reasons other than a visual change is worse than no visual gate: it trains
 * everybody to regenerate on sight, and a set that is regenerated on sight
 * asserts nothing. The four measures are listed on `settleForCapture()` in
 * `support/capture.ts`,
 * each with the drift it removes — and measure 1 is there because this suite
 * flaked on its own second run before it existed.
 */

// ---------------------------------------------------------------------------
// Geometry
// ---------------------------------------------------------------------------

/**
 * The two widths criterion 1 names.
 *
 * 412 is the width `04 §8.3` audits and the width the retained baseline
 * phone screenshots were taken at; 1440 is the desktop audit width WO-22
 * pinned its axe sweep to. Heights are `A11Y_HEIGHTS`, so the viewport this
 * file screenshots is the viewport the accessibility matrix measures — one
 * definition, not two.
 *
 * 320 is deliberately absent. It is in the axe and reflow sweeps because a
 * violation there is a real defect at a real width; as a *snapshot* it is a
 * third set of bytes over the same components in the same narrow layout, and
 * `A11Y_HEIGHTS[320]` is 568, so it is also the least informative crop.
 */
const VISUAL_WIDTHS = [412, 1440] as const;

/**
 * The one tolerance in this file, and the measurement behind it.
 *
 * FORTY-FIVE OF THE FORTY-EIGHT ARE BYTE-IDENTICAL between two forced
 * regenerations, and the three that are not differ by 4, 9 and 14 raw pixels —
 * below Playwright's own per-pixel `threshold`, so the comparator never even
 * counts them. The one render that moves enough for the comparator to see it
 * is `thread-populated` at 1440, and the cause was measured rather than
 * guessed:
 *
 *   * The briefing's `SectionRail` is `position: sticky` above 1280 px
 *     (`app/tokens.css`), and at 1440 it lays out at x = **1007.46875** — a
 *     fractional offset, the same one on every run (probed twelve times: the
 *     rect, the computed colour, the weight and the `aria-current` state are
 *     identical every time, so the DOM and the layout are deterministic).
 *   * A `sticky` box is a candidate for compositor promotion, and a promoted
 *     layer is rasterised snapped to whole device pixels while an unpromoted
 *     one is not. So the same two links are painted either at 1007.47 or at
 *     1007, half a pixel apart, and the run-to-run difference is that half
 *     pixel of glyph coverage: **124 pixels in dark, 131 in light**, bimodal,
 *     never any other value, in six full zero-tolerance runs (288
 *     comparisons). No other render failed a single comparison in those runs.
 *
 * Rejected fixes, and why. `--disable-lcd-text` on the chromium project —
 * tried, measured, made no difference, because this is subpixel *positioning*
 * and not the choice of antialiasing. Masking the rail — removes a real
 * surface from the gate to fix a rendering artefact. Injecting
 * `position: static` for the capture — makes the snapshot a picture of CSS
 * the product does not ship, and would then not notice if `sticky` were
 * removed.
 *
 * So it is a bound on the AREA that may differ, at 1.5× the largest value
 * ever observed. It is 0.015% of a 1440 × 900 frame, and the deliberate
 * 2 px shift criterion 2 asks for moves **two to three orders of magnitude**
 * more pixels than this — the PR body carries that number — so the tolerance
 * cannot swallow the regression the gate exists to catch. It bounds area
 * rather than raising `threshold`, deliberately: a colour change over a whole
 * surface stays red however small the per-pixel delta is.
 *
 * WO-D6 RE-MEASURED THIS OVER THREE FORCED REGENERATIONS AND THE BOUND STILL
 * HOLDS, with one addition worth recording rather than discovering later.
 * Forty-five of the forty-eight are byte-identical across all three. The
 * `thread-populated` pair at 1440 behaves exactly as described above —
 * bimodal, two of the three runs agreeing. The addition is `plan-review` at
 * 1440, which WO-S2 turned from a 30 px sliver of a clipped card into a
 * 742 px editor with six textareas: its left field borders carry the same
 * bimodal seam, 30 raw pixels in light and 39 in dark, at a **maximum
 * channel delta of 1 and 2**. That is an order of magnitude below the
 * per-pixel `threshold`, so Playwright counts zero differing pixels and the
 * comparator never sees it; it is recorded here because a future reader
 * measuring raw bytes will, and should know it is antialiasing on a new
 * surface rather than drift.
 */
const MAX_DIFF_PIXELS = 200;

// ---------------------------------------------------------------------------
// The inventory
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Which platforms have a committed set
// ---------------------------------------------------------------------------

/** Mirrors `snapshotPathTemplate` in `playwright.config.ts`. One meaning, two uses. */
const SNAPSHOT_ROOT = join(__dirname, "__screenshots__");

/** `{platform}` resolves to `process.platform` — `darwin`, `linux`, `win32`. */
const PLATFORM_DIR = join(SNAPSHOT_ROOT, process.platform);

/** Every platform that has one, for the guard test's message. */
function committedPlatforms(): string[] {
  if (!existsSync(SNAPSHOT_ROOT)) return [];
  return readdirSync(SNAPSHOT_ROOT, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();
}

/**
 * `all` and `changed` are the two `--update-snapshots` modes that WRITE.
 *
 * `missing` is Playwright's default and is deliberately NOT here: it writes a
 * missing snapshot and then fails the test, which is the right behaviour for
 * one new state on a platform that already has a set, and the wrong behaviour
 * for a whole platform that has none.
 */
const REGENERATING = ["all", "changed"];

/** Where the retained Gate 1 captures live, for the existence assertion. */
const BASELINE_SCREENSHOTS = join(
  __dirname,
  "..",
  "..",
  "docs",
  "revamp",
  "baseline",
  "screenshots",
);

interface VisualState {
  /** Stable id. Becomes the first segment of the snapshot file name. */
  id: string;
  /** §4 rows this render covers. */
  rows: readonly string[];
  /** The `05 §2.1` slice step this render IS, or `null` for a degraded state. */
  step: 1 | 2 | 3 | 4 | 5 | null;
  /**
   * The retained Gate 1 screenshots this render is the successor to.
   *
   * Not decoration: the inventory test below asserts every name exists under
   * `docs/revamp/baseline/screenshots/`, which is what makes criterion 1's
   * phrase "with retained baseline screenshots" a checked property rather
   * than a claim. It is also the map a reviewer uses to put the old picture
   * beside the new one.
   */
  baseline: readonly string[];
  path: string;
  arrange?: (page: Page) => Promise<void>;
  inRail?: true;
  ready: ReadyCondition;
  /**
   * Anything that must happen AFTER navigation to reach the state.
   *
   * Exactly one row needs it, and `states.ts` explains why it has no such
   * field of its own: "a `StateEntry` describes a URL plus route
   * interception, not a script". A submission failure is a script — there is
   * no URL that renders it — so the script lives here rather than widening
   * that table for one row.
   */
  drive?: (page: Page) => Promise<void>;
  /**
   * The element that IS this render's subject, scrolled into view when the
   * viewport does not already contain it.
   *
   * ONE ROW NEEDS THIS AND IT WAS FOUND BY A DUPLICATE, NOT BY DESIGN.
   * `toBeVisible()` means "has a box and is not `visibility: hidden`", not "is
   * on screen", so `reconnecting` passed its ready condition at 412 with the
   * spine's announcement below the fold — and the captured viewport was
   * `running`'s, byte for byte. Two files, one picture, and one of them
   * asserting nothing. The `no two committed snapshots are identical` test
   * below is the permanent guard; this field is the fix.
   *
   * At 1440 the announcement is already on screen, so the scroll is a no-op
   * and that snapshot is unaffected.
   */
  scrollTo?: string;
}

/** One of WO-21's rows, by id, so no path or ready condition is re-typed. */
function row(id: string): StateEntry {
  const entry = STATES.find((state) => state.id === id);
  if (entry === undefined) {
    throw new Error(
      `support/states.ts has no "${id}" row. This file names states by id so a ` +
        "rename there fails here loudly instead of silently snapshotting the " +
        "wrong page.",
    );
  }
  return entry;
}

const THREAD = `/c/${FIXTURES.populatedConversation}`;

/**
 * The five slice steps (`05-MIGRATION.md` §2.1), one resting layout each.
 *
 * Steps 2 and 4 both attach to `baseline-running`, and a naive mapping would
 * have snapshotted the same picture twice. They are not the same picture:
 * step 4's subject is the *reconnect narration*, which only exists once the
 * stream has been interrupted, and the Gate 1 set retained it as its own
 * capture (`reconnecting-desktop.png`) for that reason.
 */
const SLICE_STATES: readonly VisualState[] = [
  {
    ...row("landing"),
    step: 1,
    baseline: ["home-desktop-full.png", "home-mobile-full.png"],
  },
  {
    ...row("running"),
    step: 2,
    baseline: ["running-desktop.png"],
  },
  {
    ...row("plan-review"),
    step: 3,
    baseline: ["plan-review-desktop.png", "plan-review-mobile-full.png"],
  },
  {
    // §4 row 11, which `states.ts` correctly keeps in `DEFERRED_STATES`
    // because it is a TRANSITION rather than a resting layout the reflow
    // sweep can measure. It has a resting *appearance* all the same: the
    // browser's own `EventSource` retry loop holds the spine in
    // `reconnecting` indefinitely, which is precisely what a screenshot can
    // capture and what `capture-baseline.spec.ts:63-76` captured in Gate 1.
    id: "reconnecting",
    rows: ["11"],
    step: 4,
    baseline: ["reconnecting-desktop.png"],
    path: `${THREAD}?job=${FIXTURES.running}`,
    arrange: async (page) => {
      await interruptStream(page, FIXTURES.running);
    },
    ready: { kind: "selector", value: '[data-spine-state="reconnecting"]' },
    // Without this, the 412 capture is `running`'s viewport byte for byte.
    scrollTo: '[data-spine-part="announcement"]',
  },
  {
    ...row("thread-populated"),
    step: 5,
    baseline: [
      "conversation-populated-desktop-full.png",
      "conversation-populated-dark-desktop.png",
      "conversation-populated-mobile-full.png",
    ],
  },
];

/**
 * The degraded states that have a retained baseline screenshot.
 *
 * CRITERION 1 SAYS "THE FOUR", AND THIS LIST HAS SEVEN. That is deliberate,
 * and the arithmetic is worth writing down because nothing in `06`, `05` or
 * `00` names which four.
 *
 * Thirteen of the twenty rows in `states.ts` are degraded — a run that ended
 * badly, a write that failed, a thing that is not there. SEVEN of those
 * thirteen have a retained Gate 1 capture to be compared against; the other
 * six (`rail-error-proxy-503`, `failed-no-result`, `rate-limited-429`,
 * `unauthorized-401`, `validation-422`, `attached-status-unknown`) have none,
 * because the Gate 1 evidence run predates them — `env.ts` says so of
 * `failed-no-result` in as many words, "§4 row 15, which the Gate 1 set
 * lacked". Of the seven, two are also reached inside the slice: `expired` is
 * step 2's second half and `failed-partial` is step 5's second half. That
 * leaves FIVE the slice never reaches, not four.
 *
 * So no reading of "the four" survives contact with the state table WO-21
 * actually built, and rather than pick one and silently drop the rest, this
 * suite covers ALL SEVEN. Every reading of the criterion is then a subset of
 * what is here; the surplus is three states' worth of PNG; and the
 * alternative — a set whose membership depends on which sentence you read —
 * is the kind of coverage nobody can audit.
 */
const DEGRADED_STATES: readonly VisualState[] = [
  {
    ...row("cancelled"),
    step: null,
    baseline: ["cancelled-desktop.png"],
  },
  {
    ...row("failed-partial"),
    step: null,
    baseline: ["failed-partial-desktop.png", "failed-partial-mobile.png"],
  },
  {
    ...row("expired"),
    step: null,
    baseline: ["expired-job-desktop.png"],
  },
  {
    ...row("submission-error-500"),
    step: null,
    baseline: ["submission-error-desktop.png"],
    /**
     * THE ONE ROW WHOSE `states.ts` READY CONDITION IS NOT ENOUGH HERE.
     *
     * `states.ts` gives this row the composer textbox as its ready condition,
     * which is right for an axe sweep — the route interception is installed,
     * the page is the page the failure will happen on, and the audit is of
     * that document. For a SNAPSHOT it is not enough: nothing has been
     * submitted, so the pixels are `landing`'s and the file would be a
     * duplicate under a misleading name. So this row submits, and waits for
     * the `role="alert"` `StatusBanner` that `03 §4.9` reserves for
     * user-triggered failures.
     */
    ready: { kind: "selector", value: '[role="alert"]' },
    arrange: async (page) => {
      // Belt and braces on top of the three structural mechanisms in
      // `e2e/README.md`, "The cost boundary". The 500 below stops the journey
      // at `POST /conversations`, so `POST /research` is never reached — this
      // route makes "never reached" unreachable rather than merely true.
      await page.route(
        (url) => url.pathname === "/api/research",
        async (route) => {
          if (route.request().method() !== "POST") {
            await route.fallback();
            return;
          }
          await route.abort("blockedbyclient");
        },
      );
      // Registered second, so it wins over anything above it for this path.
      await row("submission-error-500").arrange?.(page);
    },
    drive: async (page) => {
      const { submit } = await fillComposer(
        page,
        "How should scientific research agents verify claims?",
      );
      await submit.click();
    },
  },
  {
    ...row("rail-error-upstream"),
    step: null,
    baseline: ["backend-offline-desktop.png"],
  },
  {
    ...row("thread-not-found-inline"),
    step: null,
    baseline: ["conversation-not-found-desktop.png"],
  },
  {
    ...row("route-not-found"),
    step: null,
    baseline: ["framework-not-found-desktop.png"],
  },
];

const VISUAL_STATES: readonly VisualState[] = [...SLICE_STATES, ...DEGRADED_STATES];
// ---------------------------------------------------------------------------
// Determinism
// ---------------------------------------------------------------------------

// `settleForCapture` moved to `support/capture.ts` when WO-D2's
// `readme.spec.ts` became its second caller. The four measures and the drift
// each one removes are documented there; nothing about them changed.


// ---------------------------------------------------------------------------
// The sweep
// ---------------------------------------------------------------------------

test.describe("WO-28 criterion 1 — the slice and the degraded states, light and dark, 412 and 1440", () => {
  for (const state of VISUAL_STATES) {
    for (const theme of THEMES) {
      for (const width of VISUAL_WIDTHS) {
        test(
          `${state.id} · ${theme} · ${width}px (§4 ${state.rows.join(", ")})`,
          { tag: "@visual" },
          async ({ page }, info) => {
            test.skip(
              !existsSync(PLATFORM_DIR) &&
                !REGENERATING.includes(info.config.updateSnapshots),
              `no committed snapshot set for platform "${process.platform}" ` +
                `(${PLATFORM_DIR}). This is not a regression and CI must not ` +
                "write its own baselines — a set the runner produced and then " +
                "agreed with proves nothing. Generate and REVIEW one with " +
                "`npm run e2e:visual:update` on this platform, commit it, and " +
                "these forty-eight comparisons start gating. See " +
                "e2e/README.md, 'Regenerating'.",
            );
            await page.setViewportSize({ width, height: A11Y_HEIGHTS[width] });
            // The theme axis, and the motion policy, in one call and before
            // any navigation. `emulateMedia` rather than the persisted
            // preference on purpose: `theme.spec.ts` pins a live defect in
            // which a stored `dark` is overwritten by the hydration pass, so
            // a snapshot suite that seeded `localStorage` would capture the
            // dark states in light half the time.
            await page.emulateMedia({ colorScheme: theme, reducedMotion: "reduce" });
            await state.arrange?.(page);
            await page.goto(state.path, { waitUntil: "domcontentloaded" });

            // Below `md` the rail is not in the layout and `ThreadRailBridge`
            // is not mounted until the drawer is asked for, so a rail state
            // captured without this is a picture of a page the state does not
            // occur on. At 1440 the rail is simply there.
            if (state.inRail === true && width < RAIL_ABSENT_BELOW) {
              await waitForRailMode(page, "drawer");
              await openRailDrawer(page);
            }
            await state.drive?.(page);

            // Never photograph a blank page — a screenshot of nothing is
            // stable, reproducible and worthless, which is how a visual gate
            // rots without anybody noticing.
            await expect(readyLocator(page, state.ready)).toBeVisible();
            // …and never photograph the wrong theme.
            await expect(page.locator("html")).toHaveAttribute("data-theme", theme);
            // …and never photograph a viewport the subject is not inside.
            if (state.scrollTo !== undefined) {
              await page.locator(state.scrollTo).first().scrollIntoViewIfNeeded();
            }
            await settleForCapture(page);

            await expect(page).toHaveScreenshot(`${state.id}-${theme}-${width}.png`, {
              // The viewport, not the document. `fullPage` on a long
              // briefing produces a several-thousand-pixel PNG whose bottom
              // is boilerplate, and every one of those pixels is committed
              // bytes and a chance to go red for nothing. The states whose
              // interest is below the fold have their own narrower renders.
              fullPage: false,
              // Set explicitly rather than left to the defaults, because
              // these three ARE the determinism argument and a default that
              // changes under us should change this file too.
              animations: "disabled",
              caret: "hide",
              scale: "css",
              // The one tolerance. See `MAX_DIFF_PIXELS` for the measurement.
              maxDiffPixels: MAX_DIFF_PIXELS,
            });
          },
        );
      }
    }
  }
});

// ---------------------------------------------------------------------------
// The inventory, asserted rather than described
// ---------------------------------------------------------------------------

test.describe("WO-28 criterion 1 — the inventory is what the criterion asks for", () => {
  test("the five slice steps are covered, once each", { tag: "@visual" }, () => {
    expect(
      SLICE_STATES.map((state) => state.step),
      "one resting layout per slice step, in order (05 §2.1)",
    ).toEqual([1, 2, 3, 4, 5]);
  });

  test("every degraded state is degraded, and none is a slice step", { tag: "@visual" }, () => {
    expect(DEGRADED_STATES.map((state) => state.step)).toEqual(
      DEGRADED_STATES.map(() => null),
    );
    const sliceIds = new Set(SLICE_STATES.map((state) => state.id));
    expect(
      DEGRADED_STATES.filter((state) => sliceIds.has(state.id)).map((s) => s.id),
      "a state cannot be both halves of criterion 1",
    ).toEqual([]);
  });

  test(
    "every named retained baseline screenshot exists on disk",
    { tag: "@visual" },
    () => {
      const missing = VISUAL_STATES.flatMap((state) =>
        state.baseline
          .filter((file) => !existsSync(join(BASELINE_SCREENSHOTS, file)))
          .map((file) => `${state.id} → ${file}`),
      );
      expect(
        missing,
        "criterion 1 is scoped to states 'with retained baseline screenshots', " +
          "so the correspondence has to be a checked property. A name here " +
          "with no file under docs/revamp/baseline/screenshots/ means either " +
          "the Gate 1 evidence moved or this table is wrong.",
      ).toEqual([]);
    },
  );

  test("the sweep is 12 × 2 × 2", { tag: "@visual" }, () => {
    expect(VISUAL_STATES).toHaveLength(12);
    expect(THEMES).toHaveLength(2);
    expect(VISUAL_WIDTHS).toHaveLength(2);
    expect(
      VISUAL_STATES.length * THEMES.length * VISUAL_WIDTHS.length,
      "forty-eight committed PNGs. If this number grows, the depth limit in " +
        "docs/revamp/evidence/gate-4/residual-risks.md is the thing to argue " +
        "with first — it is an accepted risk, not an oversight.",
    ).toBe(48);
  });

  /**
   * The guard on the skip above.
   *
   * The skip is right for a platform nobody has generated a set for, and it
   * would be catastrophic as a permanent condition — forty-eight green ticks
   * over forty-eight comparisons that never ran. This test never skips, so
   * deleting the whole `__screenshots__` tree turns the suite red instead of
   * quiet.
   */
  test(
    "at least one platform's baseline set is committed",
    { tag: "@visual" },
    () => {
      const platforms = committedPlatforms();
      expect(
        platforms,
        "no committed snapshot set for ANY platform. The sweep skips on a " +
          "platform with no set, which is correct for a new OS and is a " +
          "silent no-op if every set is gone — this assertion is the " +
          "difference between the two.",
      ).not.toEqual([]);
      // eslint-disable-next-line no-console
      console.log(
        `[visual] committed baseline sets: ${platforms.join(", ")}; ` +
          `this run is "${process.platform}" ` +
          `(${existsSync(PLATFORM_DIR) ? "gating" : "SKIPPING — no set"}).`,
      );
    },
  );

  /**
   * Two files, one picture — the failure a name check cannot see.
   *
   * `no two renders share a snapshot name` proves the forty-eight files are
   * forty-eight files. It does not prove they are forty-eight *pictures*, and
   * they were not: `reconnecting` at 412 was byte-identical to `running` at
   * 412, because `toBeVisible()` means "has a box", not "is on screen", and
   * the spine's reconnect announcement sits below the fold at that width. The
   * snapshot existed, passed, and asserted nothing about the state it was
   * named after — the quietest way a visual gate can be wrong.
   *
   * Byte equality is the right test rather than a similarity threshold: two
   * genuinely different states cannot compress to the same bytes, and two
   * identical captures always do.
   */
  test(
    "no two committed snapshots are identical",
    { tag: "@visual" },
    () => {
      test.skip(!existsSync(PLATFORM_DIR), "no committed set for this platform");
      const byDigest = new Map<string, string[]>();
      for (const file of readdirSync(PLATFORM_DIR).sort()) {
        if (!file.endsWith(".png")) continue;
        const digest = createHash("sha256")
          .update(readFileSync(join(PLATFORM_DIR, file)))
          .digest("hex");
        byDigest.set(digest, [...(byDigest.get(digest) ?? []), file]);
      }
      const collisions = [...byDigest.values()]
        .filter((files) => files.length > 1)
        .map((files) => files.join(" == "));
      expect(
        collisions,
        "two snapshots are the same picture under different names, so one of " +
          "them asserts nothing about the state it is named after. Either the " +
          "render never reached the state (a ready condition that passes " +
          "off-screen is the usual cause — see `scrollTo`), or the two states " +
          "genuinely do not differ inside the viewport and one of them should " +
          "not be in the table.",
      ).toEqual([]);
    },
  );

  test("no two renders share a snapshot name", { tag: "@visual" }, () => {
    const names = VISUAL_STATES.flatMap((state) =>
      THEMES.flatMap((theme) =>
        VISUAL_WIDTHS.map((width) => `${state.id}-${theme}-${width}.png`),
      ),
    );
    expect(
      new Set(names).size,
      "two renders writing one file means the second silently asserts against " +
        "the first's pixels",
    ).toBe(names.length);
  });
});
