import { existsSync } from "node:fs";
import { join } from "node:path";

import { expect, test } from "@playwright/test";
import type { Page } from "@playwright/test";

import {
  A11Y_HEIGHTS,
  RAIL_ABSENT_BELOW,
  openRailDrawer,
  waitForRailMode,
} from "./support/a11y";
import { THEMES, settleForAudit } from "./support/axe";
import { fillComposer } from "./support/composer";
import { FIXTURES } from "./support/env";
import { interruptStream } from "./support/intercept";
import { STATES, readyLocator } from "./support/states";
import type { ReadyCondition, StateEntry } from "./support/states";

/**
 * WO-28 — the visual regression baselines.
 *
 * `00-DISCOVERY.md` listed "visual regression" among the missing quality
 * tiers. This file is that tier, and it is deliberately the smallest thing
 * that closes it: Playwright's own `toHaveScreenshot`, no new dependency, no
 * hosted service, no approval UI, and a committed PNG per render.
 *
 * WHAT IS COVERED, AND THE DEPTH LIMIT THAT COMES WITH IT.
 * Twelve renders × light/dark × 412/1440 = forty-eight snapshots. That is the
 * SLICE, not the matrix: `06-WORK-ORDERS.md` §4 has thirty-one rows, WO-27's
 * axe sweep walks twenty states at three widths in both themes, and a
 * screenshot at every one of those intersections would be a hundred and
 * twenty committed PNGs that a legitimate padding change invalidates in one
 * commit. `05-MIGRATION.md` §4.2 already lists visual-regression coverage
 * depth as an accepted residual risk; the entry recording it is
 * `docs/revamp/evidence/gate-4/residual-risks.md`, and criterion 3 is that
 * the limit is written down rather than discovered later.
 *
 * WHY THE ENGINE IS CHROMIUM AND ONLY CHROMIUM.
 * The same argument `playwright.config.ts` makes for `@axe`, `@cls` and
 * `@csp`, and it is stronger here than for any of them. Text rasterisation,
 * font hinting, scrollbar geometry and form-control metrics all differ
 * between Chromium, Gecko and WebKit — so a cross-engine snapshot set is
 * three sets of bytes that go stale independently and disagree for reasons
 * that are never product defects. Cross-engine rendering drift is exactly the
 * maintenance debt this work order is scoped to exclude. The engine limit is
 * not hidden: it is `@visual` in `CHROMIUM_ONLY`, and it is stated in
 * `e2e/README.md` and in the residual-risks entry.
 *
 * THE SAME ARGUMENT APPLIES TO THE PLATFORM, WHICH IS WHY IT IS IN THE PATH.
 * `playwright.config.ts` sets `snapshotPathTemplate` to include `{platform}`,
 * so this set lives under `e2e/__screenshots__/darwin/`. macOS and Linux
 * rasterise the same font at the same size differently; a single set shared
 * between them would fail on whichever host did not produce it, which is a
 * flaky gate rather than a strict one. A Linux set is generated by running
 * `e2e:visual:update` on Linux — see `e2e/README.md`, "Regenerating".
 *
 * DETERMINISM IS THE WHOLE PRODUCT HERE. A visual gate that goes red for
 * reasons other than a visual change is worse than no visual gate: it trains
 * everybody to regenerate on sight, and a set that is regenerated on sight
 * asserts nothing. The four measures are listed on `settleForCapture()` below,
 * each with the drift it removes — and measure 1 is there because this suite
 * flaked on its own second run before it existed.
 */

// ---------------------------------------------------------------------------
// Geometry
// ---------------------------------------------------------------------------

/**
 * The two widths criterion 1 names.
 *
 * 412 is the width `04 §8.3` audits and the width the retained baseline
 * phone screenshots were taken at; 1440 is the desktop audit width WO-22
 * pinned its axe sweep to. Heights are `A11Y_HEIGHTS`, so the viewport this
 * file screenshots is the viewport the accessibility matrix measures — one
 * definition, not two.
 *
 * 320 is deliberately absent. It is in the axe and reflow sweeps because a
 * violation there is a real defect at a real width; as a *snapshot* it is a
 * third set of bytes over the same components in the same narrow layout, and
 * `A11Y_HEIGHTS[320]` is 568, so it is also the least informative crop.
 */
const VISUAL_WIDTHS = [412, 1440] as const;

/**
 * The one tolerance in this file, and the measurement behind it.
 *
 * FORTY-FIVE OF THE FORTY-EIGHT ARE BYTE-IDENTICAL between two forced
 * regenerations, and the three that are not differ by 4, 9 and 14 raw pixels —
 * below Playwright's own per-pixel `threshold`, so the comparator never even
 * counts them. The one render that moves enough for the comparator to see it
 * is `thread-populated` at 1440, and the cause was measured rather than
 * guessed:
 *
 *   * The briefing's `SectionRail` is `position: sticky` above 1280 px
 *     (`app/tokens.css`), and at 1440 it lays out at x = **1007.46875** — a
 *     fractional offset, the same one on every run (probed twelve times: the
 *     rect, the computed colour, the weight and the `aria-current` state are
 *     identical every time, so the DOM and the layout are deterministic).
 *   * A `sticky` box is a candidate for compositor promotion, and a promoted
 *     layer is rasterised snapped to whole device pixels while an unpromoted
 *     one is not. So the same two links are painted either at 1007.47 or at
 *     1007, half a pixel apart, and the run-to-run difference is that half
 *     pixel of glyph coverage: **124 pixels in dark, 131 in light**, bimodal,
 *     never any other value, in six full zero-tolerance runs (288
 *     comparisons). No other render failed a single comparison in those runs.
 *
 * Rejected fixes, and why. `--disable-lcd-text` on the chromium project —
 * tried, measured, made no difference, because this is subpixel *positioning*
 * and not the choice of antialiasing. Masking the rail — removes a real
 * surface from the gate to fix a rendering artefact. Injecting
 * `position: static` for the capture — makes the snapshot a picture of CSS
 * the product does not ship, and would then not notice if `sticky` were
 * removed.
 *
 * So it is a bound on the AREA that may differ, at 1.5× the largest value
 * ever observed. It is 0.015% of a 1440 × 900 frame, and the deliberate
 * 2 px shift criterion 2 asks for moves **two to three orders of magnitude**
 * more pixels than this — the PR body carries that number — so the tolerance
 * cannot swallow the regression the gate exists to catch. It bounds area
 * rather than raising `threshold`, deliberately: a colour change over a whole
 * surface stays red however small the per-pixel delta is.
 */
const MAX_DIFF_PIXELS = 200;

// ---------------------------------------------------------------------------
// The inventory
// ---------------------------------------------------------------------------

/** Where the retained Gate 1 captures live, for the existence assertion. */
const BASELINE_SCREENSHOTS = join(
  __dirname,
  "..",
  "..",
  "docs",
  "revamp",
  "baseline",
  "screenshots",
);

interface VisualState {
  /** Stable id. Becomes the first segment of the snapshot file name. */
  id: string;
  /** §4 rows this render covers. */
  rows: readonly string[];
  /** The `05 §2.1` slice step this render IS, or `null` for a degraded state. */
  step: 1 | 2 | 3 | 4 | 5 | null;
  /**
   * The retained Gate 1 screenshots this render is the successor to.
   *
   * Not decoration: the inventory test below asserts every name exists under
   * `docs/revamp/baseline/screenshots/`, which is what makes criterion 1's
   * phrase "with retained baseline screenshots" a checked property rather
   * than a claim. It is also the map a reviewer uses to put the old picture
   * beside the new one.
   */
  baseline: readonly string[];
  path: string;
  arrange?: (page: Page) => Promise<void>;
  inRail?: true;
  ready: ReadyCondition;
  /**
   * Anything that must happen AFTER navigation to reach the state.
   *
   * Exactly one row needs it, and `states.ts` explains why it has no such
   * field of its own: "a `StateEntry` describes a URL plus route
   * interception, not a script". A submission failure is a script — there is
   * no URL that renders it — so the script lives here rather than widening
   * that table for one row.
   */
  drive?: (page: Page) => Promise<void>;
}

/** One of WO-21's rows, by id, so no path or ready condition is re-typed. */
function row(id: string): StateEntry {
  const entry = STATES.find((state) => state.id === id);
  if (entry === undefined) {
    throw new Error(
      `support/states.ts has no "${id}" row. This file names states by id so a ` +
        "rename there fails here loudly instead of silently snapshotting the " +
        "wrong page.",
    );
  }
  return entry;
}

const THREAD = `/c/${FIXTURES.populatedConversation}`;

/**
 * The five slice steps (`05-MIGRATION.md` §2.1), one resting layout each.
 *
 * Steps 2 and 4 both attach to `baseline-running`, and a naive mapping would
 * have snapshotted the same picture twice. They are not the same picture:
 * step 4's subject is the *reconnect narration*, which only exists once the
 * stream has been interrupted, and the Gate 1 set retained it as its own
 * capture (`reconnecting-desktop.png`) for that reason.
 */
const SLICE_STATES: readonly VisualState[] = [
  {
    ...row("landing"),
    step: 1,
    baseline: ["home-desktop-full.png", "home-mobile-full.png"],
  },
  {
    ...row("running"),
    step: 2,
    baseline: ["running-desktop.png"],
  },
  {
    ...row("plan-review"),
    step: 3,
    baseline: ["plan-review-desktop.png", "plan-review-mobile-full.png"],
  },
  {
    // §4 row 11, which `states.ts` correctly keeps in `DEFERRED_STATES`
    // because it is a TRANSITION rather than a resting layout the reflow
    // sweep can measure. It has a resting *appearance* all the same: the
    // browser's own `EventSource` retry loop holds the spine in
    // `reconnecting` indefinitely, which is precisely what a screenshot can
    // capture and what `capture-baseline.spec.ts:63-76` captured in Gate 1.
    id: "reconnecting",
    rows: ["11"],
    step: 4,
    baseline: ["reconnecting-desktop.png"],
    path: `${THREAD}?job=${FIXTURES.running}`,
    arrange: async (page) => {
      await interruptStream(page, FIXTURES.running);
    },
    ready: { kind: "selector", value: '[data-spine-state="reconnecting"]' },
  },
  {
    ...row("thread-populated"),
    step: 5,
    baseline: [
      "conversation-populated-desktop-full.png",
      "conversation-populated-dark-desktop.png",
      "conversation-populated-mobile-full.png",
    ],
  },
];

/**
 * The degraded states that have a retained baseline screenshot.
 *
 * CRITERION 1 SAYS "THE FOUR", AND THIS LIST HAS SEVEN. That is deliberate,
 * and the arithmetic is worth writing down because nothing in `06`, `05` or
 * `00` names which four.
 *
 * Thirteen of the twenty rows in `states.ts` are degraded — a run that ended
 * badly, a write that failed, a thing that is not there. SEVEN of those
 * thirteen have a retained Gate 1 capture to be compared against; the other
 * six (`rail-error-proxy-503`, `failed-no-result`, `rate-limited-429`,
 * `unauthorized-401`, `validation-422`, `attached-status-unknown`) have none,
 * because the Gate 1 evidence run predates them — `env.ts` says so of
 * `failed-no-result` in as many words, "§4 row 15, which the Gate 1 set
 * lacked". Of the seven, two are also reached inside the slice: `expired` is
 * step 2's second half and `failed-partial` is step 5's second half. That
 * leaves FIVE the slice never reaches, not four.
 *
 * So no reading of "the four" survives contact with the state table WO-21
 * actually built, and rather than pick one and silently drop the rest, this
 * suite covers ALL SEVEN. Every reading of the criterion is then a subset of
 * what is here; the surplus is three states' worth of PNG; and the
 * alternative — a set whose membership depends on which sentence you read —
 * is the kind of coverage nobody can audit.
 */
const DEGRADED_STATES: readonly VisualState[] = [
  {
    ...row("cancelled"),
    step: null,
    baseline: ["cancelled-desktop.png"],
  },
  {
    ...row("failed-partial"),
    step: null,
    baseline: ["failed-partial-desktop.png", "failed-partial-mobile.png"],
  },
  {
    ...row("expired"),
    step: null,
    baseline: ["expired-job-desktop.png"],
  },
  {
    ...row("submission-error-500"),
    step: null,
    baseline: ["submission-error-desktop.png"],
    /**
     * THE ONE ROW WHOSE `states.ts` READY CONDITION IS NOT ENOUGH HERE.
     *
     * `states.ts` gives this row the composer textbox as its ready condition,
     * which is right for an axe sweep — the route interception is installed,
     * the page is the page the failure will happen on, and the audit is of
     * that document. For a SNAPSHOT it is not enough: nothing has been
     * submitted, so the pixels are `landing`'s and the file would be a
     * duplicate under a misleading name. So this row submits, and waits for
     * the `role="alert"` `StatusBanner` that `03 §4.9` reserves for
     * user-triggered failures.
     */
    ready: { kind: "selector", value: '[role="alert"]' },
    arrange: async (page) => {
      // Belt and braces on top of the three structural mechanisms in
      // `e2e/README.md`, "The cost boundary". The 500 below stops the journey
      // at `POST /conversations`, so `POST /research` is never reached — this
      // route makes "never reached" unreachable rather than merely true.
      await page.route(
        (url) => url.pathname === "/api/research",
        async (route) => {
          if (route.request().method() !== "POST") {
            await route.fallback();
            return;
          }
          await route.abort("blockedbyclient");
        },
      );
      // Registered second, so it wins over anything above it for this path.
      await row("submission-error-500").arrange?.(page);
    },
    drive: async (page) => {
      const { submit } = await fillComposer(
        page,
        "How should scientific research agents verify claims?",
      );
      await submit.click();
    },
  },
  {
    ...row("rail-error-upstream"),
    step: null,
    baseline: ["backend-offline-desktop.png"],
  },
  {
    ...row("thread-not-found-inline"),
    step: null,
    baseline: ["conversation-not-found-desktop.png"],
  },
  {
    ...row("route-not-found"),
    step: null,
    baseline: ["framework-not-found-desktop.png"],
  },
];

const VISUAL_STATES: readonly VisualState[] = [...SLICE_STATES, ...DEGRADED_STATES];

// ---------------------------------------------------------------------------
// Determinism
// ---------------------------------------------------------------------------

/**
 * Everything between "the page has arrived" and "the pixels will not move
 * again", with the drift each step removes.
 *
 * 1. **No placeholder is on screen.** `[data-skeleton-lines]` is the
 *    `Skeleton` primitive's own hook and every loading placeholder in the
 *    product is one — the rail's list, the thread route's shell, the plan
 *    editor's fields, the report's body. THIS IS THE MEASURE THAT WAS
 *    MISSING, AND IT IS WORTH SAYING WHY, BECAUSE THE OBVIOUS ONE IS NOT
 *    ENOUGH: a skeleton is *static*, so a DOM-quiescence check agrees with
 *    itself immediately and returns a page that is still waiting for its
 *    data. The first run of this suite captured `landing` with the rail's
 *    two threads loaded and the second captured it with the rail's two
 *    skeleton bars, 527 pixels apart — a flake that looks exactly like a
 *    visual regression and is not one. `Skeleton` deliberately does not
 *    animate (03 §3.7), which is what makes its absence the right signal
 *    rather than its stillness.
 * 2. **`settleForAudit`** — WO-22's two-consecutive-agreeing-samples loop over
 *    the serialised DOM, reused rather than re-implemented. A thread route
 *    paints its header from cache and fills the run panel and the event list
 *    afterwards; a capture between those moments photographs a page that
 *    never exists for a user, and photographs a *different* one next run.
 * 3. **`document.fonts.ready`** — the three families are self-hosted with
 *    `font-display: swap` (`evidence/gate-3/fonts.md`), so a capture taken
 *    before the swap is drawn in the metric-matched fallback and one taken
 *    after it is drawn in the real face. Both are real renders; only one is
 *    reproducible. The status is then asserted afterwards, because
 *    `fonts.ready` also resolves when loading FAILED.
 *    (No family is named here on purpose — `tests/fonts.test.ts` forbids it
 *    outside `app/tokens.css` and four other files, and this file is not one
 *    of them.)
 * 4. **Two `requestAnimationFrame`s** — the frame after the frame that
 *    applied the last style recalculation, so the compositor has painted what
 *    the DOM settled on.
 *
 * Three further measures are not here because they belong elsewhere:
 * `reducedMotion: "reduce"` and `colorScheme` are set on the page before
 * navigation (below); `animations: "disabled"`, `caret: "hide"` and
 * `scale: "css"` are passed to `toHaveScreenshot` itself; and the data is the
 * seeded `baseline-*` fixture set, which is the same on every run by
 * construction (`fixtures/seed.sh`, safety property 2).
 */
async function settleForCapture(page: Page): Promise<void> {
  await expect(
    page.locator("[data-skeleton-lines]"),
    "a loading placeholder was still on screen. Whatever this snapshot is a " +
      "picture of, it is not a state — see measure 1 above.",
  ).toHaveCount(0, { timeout: 20_000 });
  await settleForAudit(page);
  await page.evaluate(async () => {
    await document.fonts.ready;
    await new Promise<void>((resolve) => {
      requestAnimationFrame(() => requestAnimationFrame(() => resolve()));
    });
  });
  expect(
    await page.evaluate(() => document.fonts.status),
    "the web fonts had not finished loading when the capture was taken, so " +
      "this snapshot is of the fallback metrics and will not reproduce",
  ).toBe("loaded");
}

// ---------------------------------------------------------------------------
// The sweep
// ---------------------------------------------------------------------------

test.describe("WO-28 criterion 1 — the slice and the degraded states, light and dark, 412 and 1440", () => {
  for (const state of VISUAL_STATES) {
    for (const theme of THEMES) {
      for (const width of VISUAL_WIDTHS) {
        test(
          `${state.id} · ${theme} · ${width}px (§4 ${state.rows.join(", ")})`,
          { tag: "@visual" },
          async ({ page }) => {
            await page.setViewportSize({ width, height: A11Y_HEIGHTS[width] });
            // The theme axis, and the motion policy, in one call and before
            // any navigation. `emulateMedia` rather than the persisted
            // preference on purpose: `theme.spec.ts` pins a live defect in
            // which a stored `dark` is overwritten by the hydration pass, so
            // a snapshot suite that seeded `localStorage` would capture the
            // dark states in light half the time.
            await page.emulateMedia({ colorScheme: theme, reducedMotion: "reduce" });
            await state.arrange?.(page);
            await page.goto(state.path, { waitUntil: "domcontentloaded" });

            // Below `md` the rail is not in the layout and `ThreadRailBridge`
            // is not mounted until the drawer is asked for, so a rail state
            // captured without this is a picture of a page the state does not
            // occur on. At 1440 the rail is simply there.
            if (state.inRail === true && width < RAIL_ABSENT_BELOW) {
              await waitForRailMode(page, "drawer");
              await openRailDrawer(page);
            }
            await state.drive?.(page);

            // Never photograph a blank page — a screenshot of nothing is
            // stable, reproducible and worthless, which is how a visual gate
            // rots without anybody noticing.
            await expect(readyLocator(page, state.ready)).toBeVisible();
            // …and never photograph the wrong theme.
            await expect(page.locator("html")).toHaveAttribute("data-theme", theme);
            await settleForCapture(page);

            await expect(page).toHaveScreenshot(`${state.id}-${theme}-${width}.png`, {
              // The viewport, not the document. `fullPage` on a long
              // briefing produces a several-thousand-pixel PNG whose bottom
              // is boilerplate, and every one of those pixels is committed
              // bytes and a chance to go red for nothing. The states whose
              // interest is below the fold have their own narrower renders.
              fullPage: false,
              // Set explicitly rather than left to the defaults, because
              // these three ARE the determinism argument and a default that
              // changes under us should change this file too.
              animations: "disabled",
              caret: "hide",
              scale: "css",
              // The one tolerance. See `MAX_DIFF_PIXELS` for the measurement.
              maxDiffPixels: MAX_DIFF_PIXELS,
            });
          },
        );
      }
    }
  }
});

// ---------------------------------------------------------------------------
// The inventory, asserted rather than described
// ---------------------------------------------------------------------------

test.describe("WO-28 criterion 1 — the inventory is what the criterion asks for", () => {
  test("the five slice steps are covered, once each", { tag: "@visual" }, () => {
    expect(
      SLICE_STATES.map((state) => state.step),
      "one resting layout per slice step, in order (05 §2.1)",
    ).toEqual([1, 2, 3, 4, 5]);
  });

  test("every degraded state is degraded, and none is a slice step", { tag: "@visual" }, () => {
    expect(DEGRADED_STATES.map((state) => state.step)).toEqual(
      DEGRADED_STATES.map(() => null),
    );
    const sliceIds = new Set(SLICE_STATES.map((state) => state.id));
    expect(
      DEGRADED_STATES.filter((state) => sliceIds.has(state.id)).map((s) => s.id),
      "a state cannot be both halves of criterion 1",
    ).toEqual([]);
  });

  test(
    "every named retained baseline screenshot exists on disk",
    { tag: "@visual" },
    () => {
      const missing = VISUAL_STATES.flatMap((state) =>
        state.baseline
          .filter((file) => !existsSync(join(BASELINE_SCREENSHOTS, file)))
          .map((file) => `${state.id} → ${file}`),
      );
      expect(
        missing,
        "criterion 1 is scoped to states 'with retained baseline screenshots', " +
          "so the correspondence has to be a checked property. A name here " +
          "with no file under docs/revamp/baseline/screenshots/ means either " +
          "the Gate 1 evidence moved or this table is wrong.",
      ).toEqual([]);
    },
  );

  test("the sweep is 12 × 2 × 2", { tag: "@visual" }, () => {
    expect(VISUAL_STATES).toHaveLength(12);
    expect(THEMES).toHaveLength(2);
    expect(VISUAL_WIDTHS).toHaveLength(2);
    expect(
      VISUAL_STATES.length * THEMES.length * VISUAL_WIDTHS.length,
      "forty-eight committed PNGs. If this number grows, the depth limit in " +
        "docs/revamp/evidence/gate-4/residual-risks.md is the thing to argue " +
        "with first — it is an accepted risk, not an oversight.",
    ).toBe(48);
  });

  test("no two renders share a snapshot name", { tag: "@visual" }, () => {
    const names = VISUAL_STATES.flatMap((state) =>
      THEMES.flatMap((theme) =>
        VISUAL_WIDTHS.map((width) => `${state.id}-${theme}-${width}.png`),
      ),
    );
    expect(
      new Set(names).size,
      "two renders writing one file means the second silently asserts against " +
        "the first's pixels",
    ).toBe(names.length);
  });
});
