"""The campaign manifest: what an experiment froze before its first episode.

[`09-run-manifest-rfc.md`](../../docs/agent-engineering/09-run-manifest-rfc.md)
§5.3 gives the campaign its own sealed record beside the per-episode ones,
and [`11-benchmark-data-registry-rfc.md`](../../docs/agent-engineering/11-benchmark-data-registry-rfc.md)
§13 lists what it must contain. This module implements that record and the
three identity rules the rest of the package leans on.

**The campaign id is derived, not drawn.** RFC 09 §4 says a campaign id is
new when the protocol, arm set, task set, aggregate cap or approval scope
changes. A random id satisfies that rule only if an operator remembers to
mint one; a digest of exactly those inputs satisfies it mechanically. So
`derive_campaign_id` hashes the protocol, the registry lock and the
lineage — which means raising a cap *cannot* resume the old campaign (the
id moved), and re-planning the same protocol against the same locked
registry lands on the same id and therefore resumes.

**The lock is the registry's word, not ours.** `CampaignLock` is W02's
object, generated by W02's resolver, and this module only carries it and
pins its digest. Nothing here can widen a selection, follow an alias or
substitute a case.

**Sealing is create-once.** `CampaignManifestStore` writes the manifest,
the lock and their digest sidecars, and refuses to write over any of them.
A campaign whose manifest was overwritten would be a campaign whose
denominators are unprovable.
"""

from __future__ import annotations

import json
import os
import tempfile
from collections.abc import Mapping
from decimal import Decimal
from pathlib import Path
from typing import Annotated, Final, Literal, TypeAlias

from pydantic import Field, StringConstraints, model_validator

from src.campaign.arms import ArmId, CampaignArm
from src.campaign.errors import CampaignError
from src.contracts.kernel import (
    ContractErrorCode,
    Digest,
    ImmutableObjectRef,
    Rfc3339Utc,
    StrictContractModel,
    sha256_digest,
)
from src.contracts.registry import CampaignLock, RegistryValidationReceipt, SourceMode
from src.contracts.run_manifest import (
    CampaignBudget,
    CampaignId,
    EpisodeBudget,
    PolicyMember,
    SafeLabel,
)
from src.contracts.task_spec import TaskSpecRef

#: This package's own version, folded into every campaign it plans.
CAMPAIGN_PLANNER_VERSION: Final[str] = "1.0.0"

#: How arm order is chosen inside one query/repeat block. Named rather
#: than described so a reader of the manifest can tell an interleaved
#: campaign from a fixed-order one without reading the planner (07 §6,
#: Stage 3: "interleave arm order within each query/repeat block").
InterleavingRule: TypeAlias = Literal["predeclared-interleaved-within-block"]

#: The aggregation boundary. RFC 09 §7 and 07 §6 Stage 4 both forbid
#: mixing a controlled-source campaign with a live-retrieval one, so the
#: mode lives on the campaign rather than on an episode: two campaigns
#: that disagree here have no common summary.
CorpusModeChoice: TypeAlias = Literal["snapshot", "live"]

CampaignSeed: TypeAlias = Annotated[int, Field(ge=0, le=2**63 - 1)]
CaseId: TypeAlias = Annotated[str, StringConstraints(pattern=r"^[a-z0-9][a-z0-9-]{0,127}$")]


class DenominatorPolicy(StrictContractModel):
    """How incomplete episodes are counted, declared before any run.

    Every field is a `Literal[True]` because work-order invariant 11 is
    not a setting: failed, cancelled, timed-out, budget-stopped and
    null-scored episodes stay in the denominator. Recording them as
    unchangeable fields rather than as prose means a campaign manifest
    cannot describe a denominator that quietly drops its failures, and a
    reader does not have to trust that the analysis obeyed a convention.

    `analysis_excludes` is the one degree of freedom, and it is bounded:
    an episode leaves the analysis denominator only through a *declared*
    exclusion carrying a reason, which the ledger records and the
    reconciliation counts.
    """

    failed_episodes_counted: Literal[True] = True
    cancelled_episodes_counted: Literal[True] = True
    timed_out_episodes_counted: Literal[True] = True
    budget_stopped_episodes_counted: Literal[True] = True
    null_metric_episodes_counted: Literal[True] = True
    exclusions_require_reason: Literal[True] = True
    analysis_excludes: Literal["declared-exclusions-only"] = "declared-exclusions-only"


class CampaignLineage(StrictContractModel):
    """Why this campaign exists and which one it descends from.

    RFC 09 §11.1: raising a cap or changing the protocol creates a new
    campaign with lineage to the old one. It "may reference prior
    completed episodes but does not rewrite or re-home them", so lineage
    is a pointer, never a merge.

    Attributes:
        kind: `cap_raised` when only the money moved, `protocol_changed`
            when the design did, `rerun` when neither did and the
            operator wants a second independent execution.
        supersedes_campaign_id: The campaign this one replaces.
        supersedes_manifest_digest: That campaign's sealed manifest
            digest, so the ancestor cannot be swapped after the fact.
        rerun_of_campaign_id: Set only for `rerun`, and then equal to
            `supersedes_campaign_id` — the two names in the work order
            for one edge, kept distinct so a reader can filter on intent.
        reason: Free text for the operator, bounded and redaction-safe.
    """

    kind: Literal["cap_raised", "protocol_changed", "rerun"]
    supersedes_campaign_id: CampaignId
    supersedes_manifest_digest: Digest
    rerun_of_campaign_id: CampaignId | None = None
    reason: Annotated[str, StringConstraints(min_length=1, max_length=500)]

    @model_validator(mode="after")
    def rerun_names_its_parent(self) -> CampaignLineage:
        if self.kind == "rerun":
            if self.rerun_of_campaign_id != self.supersedes_campaign_id:
                raise ValueError("a rerun's rerun_of and supersedes must be the same campaign")
        elif self.rerun_of_campaign_id is not None:
            raise ValueError("only a rerun carries rerun_of_campaign_id")
        return self


class CampaignProtocol(StrictContractModel):
    """The experimental design, frozen. Changing any field is a new campaign.

    This is deliberately the *whole* of what RFC 09 §4 calls "protocol,
    arm set, task set, aggregate cap, or approval scope": the id derived
    from it is only as good as the fields it covers, so a field that
    changes the experiment and is not here would be a silent resume of a
    different design.
    """

    schema_kind: Literal["campaign-protocol"] = "campaign-protocol"
    schema_version: Literal["1.0.0"] = "1.0.0"
    protocol_id: SafeLabel
    stage: PolicyMember
    lane: Literal["research"] = "research"
    suite_ref: ImmutableObjectRef
    case_ids: tuple[CaseId, ...]
    arms: tuple[ArmId, ...]
    repeats: Annotated[int, Field(ge=1)]
    corpus_mode: CorpusModeChoice
    interleaving: InterleavingRule = "predeclared-interleaved-within-block"
    seed: CampaignSeed
    provider: PolicyMember
    resources: tuple[PolicyMember, ...] = ()
    approval_id: str | None = None
    episode_budget: EpisodeBudget
    campaign_budget: CampaignBudget
    denominator_policy: DenominatorPolicy = DenominatorPolicy()

    @model_validator(mode="after")
    def selection_and_caps_are_coherent(self) -> CampaignProtocol:
        if not self.case_ids or len(set(self.case_ids)) != len(self.case_ids):
            raise ValueError("case ids must be non-empty and unique")
        if not self.arms or len(set(self.arms)) != len(self.arms):
            raise ValueError("arms must be non-empty and unique")
        if self.suite_ref.kind != "benchmark_suite":
            raise ValueError("suite_ref must reference a benchmark suite")
        episode_total = Decimal(self.episode_budget.total_cost_usd_max)
        campaign_total = Decimal(self.campaign_budget.total_cost_usd_max)
        if episode_total > campaign_total:
            raise ValueError("an episode may not be permitted to spend the whole campaign cap")
        if self.approval_id is None and campaign_total > 0:
            raise ValueError(
                "a positive campaign cap without an approval id would let a "
                "declared ceiling stand in for authorization"
            )
        if self.approval_id is not None and campaign_total == 0:
            raise ValueError("a zero-cost campaign cannot carry an approval id")
        return self

    @property
    def chargeable(self) -> bool:
        """Whether this protocol plans any metered work at all."""
        return Decimal(self.campaign_budget.total_cost_usd_max) > 0


class CampaignManifestPayload(StrictContractModel):
    """Everything the campaign froze, in one canonically hashable object."""

    schema_kind: Literal["campaign-manifest"] = "campaign-manifest"
    schema_version: Literal["1.0.0"] = "1.0.0"
    campaign_id: CampaignId
    created_at: Rfc3339Utc
    created_by: SafeLabel
    protocol: CampaignProtocol
    protocol_digest: Digest
    lock: CampaignLock
    lock_digest: Digest
    registry_validation_receipt: RegistryValidationReceipt
    registry_validation_receipt_ref: ImmutableObjectRef
    arms: tuple[CampaignArm, ...]
    task_refs: tuple[TaskSpecRef, ...]
    expected_episode_count: Annotated[int, Field(ge=1)]
    planned_episode_count: Annotated[int, Field(ge=0)]
    excluded_episode_count: Annotated[int, Field(ge=0)]
    output_root: Annotated[str, StringConstraints(min_length=1, max_length=200)]
    lineage: CampaignLineage | None = None

    @model_validator(mode="after")
    def digests_and_counts_are_self_consistent(self) -> CampaignManifestPayload:
        if self.protocol_digest != sha256_digest(self.protocol):
            raise ValueError("protocol digest does not address the protocol")
        if self.lock_digest != sha256_digest(self.lock):
            raise ValueError("lock digest does not address the lock")
        if self.registry_validation_receipt.lock_digest != self.lock_digest:
            raise ValueError("registry validation receipt validated a different lock")
        if self.registry_validation_receipt_ref.digest != sha256_digest(
            self.registry_validation_receipt
        ):
            raise ValueError("validation receipt ref does not address the receipt")
        if self.registry_validation_receipt_ref.kind != "registry_validation_receipt":
            raise ValueError("validation receipt ref has the wrong kind")
        protocol = self.protocol
        if self.lock.suite_ref != protocol.suite_ref:
            raise ValueError("lock and protocol name different suites")
        if self.lock.repeats != protocol.repeats:
            raise ValueError("lock and protocol declare different repeat counts")
        if tuple(ref.id for ref in self.lock.case_refs) != protocol.case_ids:
            raise ValueError("lock and protocol select different cases")
        expected_mode = (
            SourceMode.LIVE if protocol.corpus_mode == "live" else SourceMode.SNAPSHOT
        )
        if self.lock.source_mode is not expected_mode:
            raise ValueError("lock and protocol disagree about the corpus mode")
        declared = tuple(arm.arm_id for arm in self.arms)
        if declared != protocol.arms:
            raise ValueError("declared arms do not match the protocol's arm set")
        if len(self.task_refs) != len(protocol.case_ids):
            raise ValueError("the campaign needs exactly one TaskSpec per selected case")
        digests = [ref.full_digest for ref in self.task_refs]
        if len(set(digests)) != len(digests):
            raise ValueError("two selected cases compiled to the same TaskSpec")
        block_count = len(protocol.case_ids) * protocol.repeats
        runnable = sum(1 for arm in self.arms if arm.runnable)
        if self.expected_episode_count != block_count * len(self.arms):
            raise ValueError("expected episode count is not cases x repeats x arms")
        if self.planned_episode_count != block_count * runnable:
            raise ValueError("planned episode count is not cases x repeats x runnable arms")
        if self.planned_episode_count + self.excluded_episode_count != (
            self.expected_episode_count
        ):
            raise ValueError("planned and excluded episodes do not account for the matrix")
        if self.lock.expected_denominator != block_count:
            raise ValueError("lock denominator disagrees with cases x repeats")
        expected_id = derive_campaign_id(
            protocol_digest=self.protocol_digest,
            lock_digest=self.lock_digest,
            lineage=self.lineage,
        )
        if self.campaign_id != expected_id:
            raise ValueError(
                "campaign id is not derived from this protocol, lock and lineage"
            )
        return self


class CampaignIntegrity(StrictContractModel):
    """The campaign manifest's digest header, in the shared v1 profile."""

    algorithm: Literal["sha256"] = "sha256"
    digest_profile: Literal["agent-contract-json/v1"] = "agent-contract-json/v1"
    canonicalization: Literal["RFC8785"] = "RFC8785"
    payload_sha256: Digest


class CampaignManifestV1(StrictContractModel):
    """The sealed campaign record, digest first."""

    schema_kind: Literal["campaign-manifest-envelope"] = "campaign-manifest-envelope"
    schema_version: Literal["1.0.0"] = "1.0.0"
    integrity: CampaignIntegrity
    payload: CampaignManifestPayload

    @model_validator(mode="after")
    def verify_integrity(self) -> CampaignManifestV1:
        if self.integrity.payload_sha256 != sha256_digest(self.payload):
            raise ValueError("campaign manifest digest does not address its payload")
        return self


def derive_campaign_id(
    *,
    protocol_digest: Digest,
    lock_digest: Digest,
    lineage: CampaignLineage | None,
) -> str:
    """Derive the campaign id from exactly what RFC 09 §4 says defines one.

    Deterministic on purpose. Two consequences, and both are the point:
    re-planning an unchanged protocol against an unchanged lock produces
    the same id and therefore resumes the same campaign, and raising a
    cap produces a different id and therefore *cannot*.

    Lineage participates so that a rerun of an unchanged protocol is a
    distinct campaign rather than a collision with its own parent.

    Args:
        protocol_digest: Digest of the frozen `CampaignProtocol`.
        lock_digest: Digest of W02's `CampaignLock`.
        lineage: The lineage edge, when this campaign supersedes one.

    Returns:
        A `camp_`-prefixed id, 32 hex characters of SHA-256.
    """
    material = {
        "planner_version": CAMPAIGN_PLANNER_VERSION,
        "protocol_digest": protocol_digest,
        "lock_digest": lock_digest,
        "lineage": lineage.model_dump(mode="json") if lineage is not None else None,
    }
    return "camp_" + sha256_digest(material).removeprefix("sha256:")[:32]


def seal_campaign_manifest(payload: CampaignManifestPayload) -> CampaignManifestV1:
    """Hash a validated payload once and wrap it in its envelope."""
    return CampaignManifestV1(
        integrity=CampaignIntegrity(payload_sha256=sha256_digest(payload)),
        payload=payload,
    )


class CampaignManifestStore:
    """Create-once filesystem store for a campaign's four sealed files.

    Mirrors `ManifestFileStore`'s discipline at campaign scale: write to a
    temporary file in the destination directory, fsync, then `os.link`
    into place so an existing file is a hard failure rather than a silent
    overwrite. A campaign directory whose manifest was replaced could not
    prove which protocol produced its episodes, so replacement is refused
    rather than warned about.
    """

    manifest_filename: Final[str] = "campaign-manifest.json"
    manifest_sidecar: Final[str] = "campaign-manifest.sha256"
    lock_filename: Final[str] = "campaign-lock.json"
    lock_sidecar: Final[str] = "campaign-lock.sha256"

    def seal(self, directory: Path, manifest: CampaignManifestV1) -> tuple[Path, ...]:
        """Write the manifest, the lock and both digest sidecars.

        Args:
            directory: Campaign root; created if absent.
            manifest: The sealed campaign manifest.

        Returns:
            The four written paths, in the order above.

        Raises:
            CampaignError: Any of the four already exists.
        """
        directory.mkdir(parents=True, exist_ok=True)
        payload = manifest.payload
        files = (
            (self.manifest_filename, _canonical_line(manifest)),
            (
                self.manifest_sidecar,
                f"{manifest.integrity.payload_sha256}  {self.manifest_filename}\n",
            ),
            (self.lock_filename, _canonical_line(payload.lock)),
            (self.lock_sidecar, f"{payload.lock_digest}  {self.lock_filename}\n"),
        )
        for name, _ in files:
            if (directory / name).exists():
                raise CampaignError(
                    f"refusing to overwrite a sealed campaign file: {name}"
                )
        written: list[Path] = []
        for name, text in files:
            written.append(_atomic_create(directory, name, text))
        return tuple(written)

    def load(self, directory: Path) -> CampaignManifestV1:
        """Read and verify a sealed campaign manifest.

        Raises:
            CampaignError: The manifest or its sidecar is missing,
                unparseable, or disagrees with the recorded digest.
        """
        target = directory / self.manifest_filename
        sidecar = directory / self.manifest_sidecar
        if not target.is_file() or not sidecar.is_file():
            raise CampaignError("campaign manifest and digest sidecar must both exist")
        try:
            manifest = CampaignManifestV1.model_validate_json(
                target.read_text(encoding="utf-8")
            )
        except (OSError, ValueError) as exc:
            raise CampaignError(f"campaign manifest is invalid: {exc}") from exc
        parts = sidecar.read_text(encoding="utf-8").strip().split()
        if parts != [manifest.integrity.payload_sha256, self.manifest_filename]:
            raise CampaignError(
                "campaign manifest digest sidecar mismatch",
                code=ContractErrorCode.DIGEST_INVALID,
            )
        return manifest


def _canonical_line(value: object) -> str:
    from src.contracts.kernel import canonical_json

    return canonical_json(value) + "\n"


def _atomic_create(directory: Path, name: str, text: str) -> Path:
    """Create `directory/name` atomically, refusing to replace an existing file."""
    target = directory / name
    handle_fd, temporary_name = tempfile.mkstemp(prefix=f".{name}.", dir=directory)
    temporary = Path(temporary_name)
    try:
        with os.fdopen(handle_fd, "w", encoding="utf-8") as handle:
            handle.write(text)
            handle.flush()
            os.fsync(handle.fileno())
        try:
            os.link(temporary, target)
        except FileExistsError as exc:
            raise CampaignError(f"refusing to overwrite {name}") from exc
        return target
    finally:
        temporary.unlink(missing_ok=True)


def write_json(path: Path, payload: Mapping[str, object]) -> None:
    """Write one derived, rewritable campaign artifact.

    Used for the ledger and the summary, which are *derived* views and are
    rewritten every reconciliation — unlike the manifest and the lock,
    which are sealed once. Keeping the two write paths visibly different
    is the point: a file written by this function is not evidence of what
    was frozen.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


__all__ = [
    "CAMPAIGN_PLANNER_VERSION",
    "CampaignIntegrity",
    "CampaignLineage",
    "CampaignManifestPayload",
    "CampaignManifestStore",
    "CampaignManifestV1",
    "CampaignProtocol",
    "CaseId",
    "CorpusModeChoice",
    "DenominatorPolicy",
    "InterleavingRule",
    "derive_campaign_id",
    "seal_campaign_manifest",
    "write_json",
]
